-- ==========================================================================
-- MSREC — Committee member protocol review
-- (Protocols for Committee Review, Reviewer Recommendations,
--  Conflict & Recusal, Committee Deliberations)
-- ==========================================================================
-- Run once in the Supabase SQL editor. Idempotent: safe to re-run.
--
-- The pages read protocols (applications), reviewer recommendations
-- (review_assignments) and meetings/agenda items from tables that already
-- exist. These two tables are the only new ones:
--
--   committee_protocol_declarations  one row per (protocol, member): "no
--       conflict" or a described conflict, optionally with a recusal request.
--       A declared conflict is mirrored into committee_conflict_declarations
--       (linked by conflict_record_id) so it also appears on the
--       Secretariat/admin Conflict Records page.
--   committee_deliberation_posts     the committee's discussion thread on a
--       protocol (comments, questions, concerns, support; one reply level).
-- ---------------------------------------------------------------------

begin;

create table if not exists public.committee_protocol_declarations (
    id                  bigint generated by default as identity primary key,
    application_id      bigint not null references public.applications (id) on delete cascade,
    user_id             bigint not null references public.users (id) on delete cascade,

    has_conflict        boolean not null default false,
    conflict_type       varchar(14) not null default ''
                        check (conflict_type in ('', 'financial', 'personal', 'professional', 'institutional', 'supervisory', 'other')),
    description         text not null default '',
    wants_recusal       boolean not null default false,
    status              varchar(8) not null default 'clear'
                        check (status in ('clear', 'pending', 'recused', 'cleared')),

    conflict_record_id  bigint references public.committee_conflict_declarations (id) on delete set null,

    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),

    unique (application_id, user_id)
);

comment on table public.committee_protocol_declarations is 'A committee member''s conflict-of-interest declaration on one protocol. committee_dashboard.models.ProtocolDeclaration maps onto this table 1:1.';

create index if not exists committee_protocol_declarations_application_id_idx on public.committee_protocol_declarations (application_id);
create index if not exists committee_protocol_declarations_user_id_idx on public.committee_protocol_declarations (user_id);
create index if not exists committee_protocol_declarations_conflict_record_id_idx on public.committee_protocol_declarations (conflict_record_id);


create table if not exists public.committee_deliberation_posts (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references public.applications (id) on delete cascade,
    author_id       bigint not null references public.users (id) on delete cascade,
    parent_id       bigint references public.committee_deliberation_posts (id) on delete cascade,

    kind            varchar(8) not null default 'comment'
                    check (kind in ('comment', 'question', 'concern', 'support')),
    body            text not null,
    is_deleted      boolean not null default false,

    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

comment on table public.committee_deliberation_posts is 'One message in the committee''s discussion of a protocol. committee_dashboard.models.DeliberationPost maps onto this table 1:1.';

create index if not exists committee_deliberation_posts_application_id_idx on public.committee_deliberation_posts (application_id);
create index if not exists committee_deliberation_posts_author_id_idx on public.committee_deliberation_posts (author_id);
create index if not exists committee_deliberation_posts_parent_id_idx on public.committee_deliberation_posts (parent_id);

-- Same deny-by-default-with-service_role-bypass posture as the rest of schema.sql.
alter table public.committee_protocol_declarations enable row level security;
alter table public.committee_deliberation_posts enable row level security;

drop policy if exists "service_role full access to committee_protocol_declarations" on public.committee_protocol_declarations;
create policy "service_role full access to committee_protocol_declarations"
    on public.committee_protocol_declarations for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to committee_deliberation_posts" on public.committee_deliberation_posts;
create policy "service_role full access to committee_deliberation_posts"
    on public.committee_deliberation_posts for all
    to service_role
    using (true) with check (true);

commit;
