-- ==========================================================================
-- MSREC — Committee member "Meeting Agenda" notes
-- ==========================================================================
-- Run this once in the Supabase SQL editor (Dashboard -> SQL Editor).
-- Safe to re-run: every statement is idempotent.
--
-- Mirrors meetings.models.AgendaItemNote. Everything else the committee
-- member's Dashboard / Committee Meetings / Meeting Agenda pages show is
-- read from tables that already exist (meetings, meeting_participants,
-- meeting_agenda_items, applications); RSVP writes to
-- meeting_participants.rsvp_status. This is the only new table: a
-- member's private working notes on an agenda item, and whether they've
-- marked that item "prepared". One row per (agenda item, member).
-- ---------------------------------------------------------------------

begin;

create table if not exists public.meeting_agenda_notes (
    id              bigint generated by default as identity primary key,
    agenda_item_id  bigint not null references public.meeting_agenda_items (id) on delete cascade,
    user_id         bigint not null references public.users (id) on delete cascade,

    note            text not null default '',
    is_reviewed     boolean not null default false,

    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),

    unique (agenda_item_id, user_id)
);

comment on table public.meeting_agenda_notes is 'A committee member''s private notes + "prepared" flag on one agenda item. meetings.models.AgendaItemNote maps onto this table 1:1.';

create index if not exists meeting_agenda_notes_agenda_item_id_idx on public.meeting_agenda_notes (agenda_item_id);
create index if not exists meeting_agenda_notes_user_id_idx on public.meeting_agenda_notes (user_id);

-- Same deny-by-default-with-service_role-bypass posture as every other
-- table in schema.sql (the Django app connects as the service role).
alter table public.meeting_agenda_notes enable row level security;

drop policy if exists "service_role full access to meeting_agenda_notes" on public.meeting_agenda_notes;
create policy "service_role full access to meeting_agenda_notes"
    on public.meeting_agenda_notes for all
    to service_role
    using (true) with check (true);

commit;
