-- MSREC: per-user "delete" for notifications.
--
-- Equivalent of Django migration notifications/0003_notification_dismissals.py.
-- You do NOT need to run this if you run `python manage.py migrate` -- it is
-- here for running by hand in the Supabase SQL Editor. Safe to run twice.
--
-- Notifications are shared by everyone who holds a role, so deleting one must
-- not delete the shared row. This table records "user X deleted notification
-- Y"; the notifications page, the topbar bell and the unread counts all skip
-- a notification for a user who has a row here. Nothing else changes: the
-- notifications and notification_reads tables are untouched.

CREATE TABLE IF NOT EXISTS notification_dismissals (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dismissed_at    timestamptz NOT NULL DEFAULT now(),
  notification_id bigint NOT NULL
    REFERENCES notifications (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  user_id         bigint NOT NULL
    REFERENCES users (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT unique_notification_dismissal_per_user UNIQUE (notification_id, user_id)
);

CREATE INDEX IF NOT EXISTS notification_dismissals_notification_id_900c1ae3
  ON notification_dismissals (notification_id);
CREATE INDEX IF NOT EXISTS notification_dismissals_user_id_a6d5006d
  ON notification_dismissals (user_id);

-- Only if you ran this file by hand: tell Django the migration is done so
-- `manage.py migrate` doesn't try to create the table again.
INSERT INTO django_migrations (app, name, applied)
SELECT 'notifications', '0003_notification_dismissals', now()
WHERE NOT EXISTS (
  SELECT 1 FROM django_migrations
  WHERE app = 'notifications' AND name = '0003_notification_dismissals'
);

-- Check:
-- SELECT count(*) FROM notification_dismissals;
