-- MSREC: Quality Assurance notes on a reviewer's completed assessment.
--
-- Equivalent of Django migration reviewer_dashboard/0007_reviewqanote.py.
-- You do NOT need to run this if you run `python manage.py migrate` -- it is
-- here for running by hand in the Supabase SQL Editor. Safe to run twice.
--
-- One row = one note from QA staff (Secretariat, Chair or Admin -- see
-- reviewer_dashboard.qa.is_qa_staff, there's no dedicated "QA officer" role)
-- on one reviewer's completed review_assignments row.
--
--   action_required = true  -- a "please fix this" request. Surfaces on the
--                              Reviewer/Committee dashboard's Pending QA
--                              Actions until the reviewer resolves it.
--   action_required = false -- pure feedback with nothing to act on.
--
-- Both kinds live in the same table -- QA Feedback shows every note ever
-- raised (resolved or not); Pending QA Actions is just the open subset
-- (status = 'open' AND action_required = true).

BEGIN;

CREATE TABLE IF NOT EXISTS review_qa_notes (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_required  boolean     NOT NULL,
  message          text        NOT NULL,
  status           varchar(20) NOT NULL,
  created_at       timestamptz NOT NULL,
  resolved_at      timestamptz NULL,
  resolution_note  text        NOT NULL,
  assignment_id    bigint      NOT NULL,
  raised_by_id     bigint      NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'review_qa_notes_assignment_id_bdbadf22_fk_review_assignments_id'
  ) THEN
    ALTER TABLE review_qa_notes
      ADD CONSTRAINT review_qa_notes_assignment_id_bdbadf22_fk_review_assignments_id
      FOREIGN KEY (assignment_id) REFERENCES review_assignments (id)
      DEFERRABLE INITIALLY DEFERRED;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'review_qa_notes_raised_by_id_14b2cb71_fk_users_id'
  ) THEN
    ALTER TABLE review_qa_notes
      ADD CONSTRAINT review_qa_notes_raised_by_id_14b2cb71_fk_users_id
      FOREIGN KEY (raised_by_id) REFERENCES users (id)
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS review_qa_notes_assignment_id_bdbadf22 ON review_qa_notes (assignment_id);
CREATE INDEX IF NOT EXISTS review_qa_notes_raised_by_id_14b2cb71 ON review_qa_notes (raised_by_id);

-- Only if you ran this file by hand: tell Django the migration is done so
-- `manage.py migrate` doesn't try to create the table again.
INSERT INTO django_migrations (app, name, applied)
SELECT 'reviewer_dashboard', '0007_reviewqanote', now()
WHERE NOT EXISTS (
  SELECT 1 FROM django_migrations
  WHERE app = 'reviewer_dashboard' AND name = '0007_reviewqanote'
);

COMMIT;

-- Check:
-- SELECT id, assignment_id, action_required, status, created_at FROM review_qa_notes ORDER BY created_at DESC LIMIT 20;

-- ============================================================================
-- Undo (removes the feature's table -- only do this if you are rolling the
-- code back too)
-- ============================================================================
--   DROP TABLE IF EXISTS review_qa_notes;
--   DELETE FROM django_migrations WHERE app = 'reviewer_dashboard' AND name = '0007_reviewqanote';
