-- ==========================================================================
-- MSREC — Supabase / Postgres schema for accounts (signup, login, roles)
-- ==========================================================================
--
-- WHAT THIS IS
-- Django owns this schema via accounts/migrations/0001_initial.py through
-- 0007_passwordresetcode.py (and every other app's migrations below it).
-- The columns, types and constraints below are a byte-for-byte translation
-- of those migrations into hand-written SQL, for two reasons:
--   1. You asked for something you can paste into the Supabase SQL editor
--      and inspect/run directly.
--   2. It gives you RLS policies, which a Django migration never writes.
--
-- WHICH PATH TO ACTUALLY USE
--   Recommended (simplest, and what was tested end-to-end for this build):
--     1. Create a Supabase project, copy its Postgres connection string.
--     2. Put it in .env as DATABASE_URL=postgresql://... (see .env.example).
--     3. Run: python manage.py migrate
--     Django creates every table below itself. You never need this file.
--
--   Alternative (if you'd rather provision the tables from the Supabase
--   SQL editor first, e.g. to review/tweak them before Django touches
--   anything):
--     1. Run this whole file in the Supabase SQL editor.
--     2. Run: python manage.py migrate --fake-initial
--        (tells Django "these tables already exist with this shape, just
--        record the migration as applied" instead of trying to CREATE them
--        again).
--
-- Either path lands on the identical schema, so accounts/models.py (the
-- Django User model) works unmodified against it either way.
--
-- WHY RLS BARELY MATTERS HERE, BUT IS ENABLED ANYWAY
-- The Django app authenticates with Django's own session-based login
-- (accounts/views.py) and talks to Postgres directly over DATABASE_URL,
-- using the Postgres role from your Supabase connection string — normally
-- a privileged role that bypasses RLS entirely. Nothing in this project
-- calls Supabase's PostgREST/GoTrue API with the anon or authenticated
-- JWT, so these policies are not what protects this app's users right now
-- (Django's own auth does that). RLS is turned on anyway, with a
-- deny-by-default posture, as a safety net for the day something else
-- (Supabase's auto-generated REST API, a future serverless function,
-- someone poking at the anon key) tries to query these tables directly.
-- ==========================================================================


-- ---------------------------------------------------------------------
-- users
-- Mirrors accounts.models.User. One row per MSREC account. Every signup
-- lands here with role='applicant' (no approval needed — applying is the
-- default capability). wants_reviewer/wants_committee + their *_status
-- columns track the two roles that DO need an admin's sign-off; see
-- reviewer_status/committee_status below and role_approval_logs for the
-- audit trail admin_dashboard's Accounts page writes to.
-- ---------------------------------------------------------------------
create table if not exists public.users (
    id                      bigint generated by default as identity primary key,

    -- Auth (Django's AbstractBaseUser + PermissionsMixin contract)
    password                varchar(128) not null,
    last_login              timestamptz,
    is_superuser            boolean not null default false,
    is_staff                boolean not null default false,
    is_active               boolean not null default true,

    -- Identity
    email                   varchar(254) not null unique,
    date_joined             timestamptz not null default now(),

    -- Personal info (from the signup form's Personal Information section)
    first_name              varchar(150) not null,
    middle_name             varchar(150) not null default '',
    last_name               varchar(150) not null,
    title                   varchar(20)  not null default '',
    phone                   varchar(40)  not null default '',
    country_residence       varchar(120) not null default '',
    highest_qualification   varchar(150) not null default '',

    -- Institution / Professional Information section
    institution             varchar(200) not null default '',
    department              varchar(200) not null default '',
    position                varchar(150) not null default '',
    institution_country     varchar(120) not null default '',
    institution_address     varchar(255) not null default '',
    profile_url             varchar(200) not null default '',
    no_institution           boolean not null default false,
    orcid                    varchar(40)  not null default '',

    -- Institution / Affiliation page (dashboards/applicant/institution-
    -- affiliation.html) -- extra detail an applicant fills in/edits after
    -- signup, once they know more than they did when they first registered.
    faculty                 varchar(200) not null default '',
    staff_student_id        varchar(100) not null default '',
    hod_name                varchar(200) not null default '',
    hod_email               varchar(254) not null default '',
    irb_name                varchar(200) not null default '',
    irb_reference_no        varchar(100) not null default '',

    -- Profile & Security page toggles (dashboards/applicant/profile-
    -- security.html). Persisted preferences only -- no OTP/SMS provider is
    -- wired up yet, so these aren't (currently) enforced at login.
    two_factor_app          boolean not null default false,
    two_factor_sms          boolean not null default false,
    notify_new_signin       boolean not null default true,

    -- Notification delivery preferences + read-cursor (Reviewer dashboard's
    -- Notifications page, dashboards/reviewer/notifications.html, and any
    -- other role's notification bell -- not reviewer-specific despite
    -- living on the one page that currently exposes the toggles).
    notify_email_alerts     boolean not null default true,
    notify_sms_alerts       boolean not null default false,
    notify_weekly_digest    boolean not null default true,
    notifications_last_read_at timestamptz,

    -- Object path inside Supabase Storage. Three possible shapes, told
    -- apart by prefix (see accounts/context_processors.py profile_avatar()):
    --   "reviewers/<id>/..." -> public "profile" bucket (photo changed
    --     from a reviewer's Profile & Expertise page --
    --     reviewer_dashboard/storage.py). Create this bucket in the
    --     Supabase dashboard (Storage > New bucket, public) if it
    --     doesn't exist yet -- nothing here provisions it automatically.
    --   "avatars/<id>/..." -> public "application" bucket (photo changed
    --     from Profile & Security -- applicant_dashboard/storage.py).
    --   anything else      -> private "signup" bucket (photo attached at
    --     signup -- accounts/storage.py), needs a freshly-signed URL.
    profile_photo_path      varchar(500) not null default '',

    -- Primary role: which dashboard this account lands on after login
    -- (see User.dashboard_url_name() in accounts/models.py).
    role                    varchar(20) not null default 'applicant'
                            check (role in ('applicant', 'reviewer', 'committee', 'chair', 'secretariat', 'admin')),

    -- Reviewer role request + its extra signup-form answers
    wants_reviewer          boolean not null default false,
    reviewer_status         varchar(20) not null default 'not_requested'
                            check (reviewer_status in ('not_requested', 'pending', 'approved', 'rejected')),
    reviewer_profile        jsonb not null default '{}'::jsonb,
    -- Secretariat-managed (Reviewer Directory), not applicant-set -- see
    -- User.Availability / accounts/models.py.
    reviewer_availability   varchar(20) not null default 'available'
                            check (reviewer_availability in ('available', 'limited', 'unavailable')),

    -- Committee role request + its extra signup-form answers
    wants_committee         boolean not null default false,
    committee_status        varchar(20) not null default 'not_requested'
                            check (committee_status in ('not_requested', 'pending', 'approved', 'rejected')),
    committee_profile       jsonb not null default '{}'::jsonb,

    -- Applicant-specific signup-form answers, and whether this account
    -- actually ticked "Applicant / Researcher" at signup at all --
    -- Reviewer/Committee can be requested on their own, without
    -- Applicant, and someone who did that shouldn't be told they have
    -- Applicant access while their request is pending (see
    -- User.dashboard_url_name() / awaiting_role_only in accounts/models.py).
    wants_applicant         boolean not null default true,
    applicant_profile       jsonb not null default '{}'::jsonb
);

comment on table public.users is 'MSREC accounts. Django''s AUTH_USER_MODEL (accounts.User) maps onto this table 1:1.';
comment on column public.users.role is 'Primary/active role — decides which dashboard a login lands on.';
comment on column public.users.wants_applicant is 'Whether Applicant/Researcher was actually ticked at signup — false means this account requested Reviewer/Committee only and gets no Applicant dashboard access while pending.';
comment on column public.users.reviewer_status is 'not_requested | pending | approved | rejected — set to pending at signup when wants_reviewer is checked, flipped by an admin in Accounts > Pending Approval.';
comment on column public.users.committee_status is 'Same lifecycle as reviewer_status, for the Committee Member role.';
comment on column public.users.reviewer_availability is 'available | limited | unavailable — shown and changed on secretariat_dashboard''s Reviewer Directory, independent of reviewer_status.';
comment on column public.users.notifications_last_read_at is 'Timestamp of the last time this user opened their Notifications page — drives the unread badge/count, not a per-notification read table.';

-- Case-insensitive login lookups and the accounts-page tab counts both
-- filter on these constantly.
create index if not exists users_email_lower_idx on public.users (lower(email));
create index if not exists users_role_idx on public.users (role);
create index if not exists users_reviewer_status_idx on public.users (reviewer_status) where reviewer_status = 'pending';
create index if not exists users_committee_status_idx on public.users (committee_status) where committee_status = 'pending';


-- ---------------------------------------------------------------------
-- role_approval_logs
-- Audit trail for every admin approve/reject decision on a reviewer or
-- committee request (accounts.models.RoleApprovalLog). Written by
-- admin_dashboard.views.accounts() each time an admin acts on a request.
-- ---------------------------------------------------------------------
create table if not exists public.role_approval_logs (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references public.users (id) on delete cascade,
    role        varchar(20) not null
                check (role in ('applicant', 'reviewer', 'committee', 'chair', 'secretariat', 'admin')),
    action      varchar(20) not null check (action in ('approved', 'rejected')),
    acted_by_id bigint references public.users (id) on delete set null,
    note        varchar(255) not null default '',
    created_at  timestamptz not null default now()
);

comment on table public.role_approval_logs is 'Audit trail: who approved/rejected which reviewer or committee request, and when.';

create index if not exists role_approval_logs_user_id_idx on public.role_approval_logs (user_id);
create index if not exists role_approval_logs_created_at_idx on public.role_approval_logs (created_at desc);


-- ---------------------------------------------------------------------
-- audit_logs
-- General-purpose activity trail (accounts.models.AuditLog) -- covers
-- everything role_approval_logs above doesn't: application status
-- changes, account suspend/activate/delete/edit, reviewer assignment
-- create/withdraw, and sign-ins. target_type/target_id/target_label are
-- a loose pointer rather than a real FK -- the target row (a user, an
-- application) can be deleted later while the log entry itself must
-- still read sensibly, so this deliberately never cascades off it.
-- ---------------------------------------------------------------------
create table if not exists public.audit_logs (
    id            bigint generated by default as identity primary key,
    actor_id      bigint references public.users (id) on delete set null,
    action        varchar(64) not null,
    target_type   varchar(64) not null default '',
    target_id     varchar(64) not null default '',
    target_label  varchar(255) not null default '',
    description   text not null default '',
    created_at    timestamptz not null default now()
);

comment on table public.audit_logs is 'General activity trail: who did what, to what, and when -- across the whole platform.';

create index if not exists audit_logs_actor_id_idx on public.audit_logs (actor_id);
create index if not exists audit_logs_action_idx on public.audit_logs (action);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);


-- ---------------------------------------------------------------------
-- password_reset_codes
-- Mirrors accounts.models.PasswordResetCode. One row per 6-digit code
-- issued by the Forgot Password flow (pages:forgot_password /
-- pages:reset_password, accounts/views.py) -- never reused or edited in
-- place, so this doubles as an audit trail of every reset attempt
-- against an account, the same "one row per attempt" idea as
-- role_approval_logs above. A code is spent (used_at set) the moment a
-- reset succeeds; every other still-open code for that user is spent in
-- the same update, so an old code from an earlier request can never
-- outlive a successful reset.
-- ---------------------------------------------------------------------
create table if not exists public.password_reset_codes (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references public.users (id) on delete cascade,

    code        varchar(6) not null,
    created_at  timestamptz not null default now(),
    expires_at  timestamptz not null,
    used_at     timestamptz
);

comment on table public.password_reset_codes is 'Forgot Password 6-digit codes, one row per code issued. accounts.models.PasswordResetCode maps onto this table 1:1.';
comment on column public.password_reset_codes.used_at is 'Set the moment a reset succeeds (or the code is superseded by a later reset) -- null means still open and unused.';

create index if not exists password_reset_codes_user_id_idx on public.password_reset_codes (user_id);
create index if not exists password_reset_codes_user_open_idx on public.password_reset_codes (user_id, created_at desc) where used_at is null;

alter table public.password_reset_codes enable row level security;

drop policy if exists "service_role full access to password_reset_codes" on public.password_reset_codes;
create policy "service_role full access to password_reset_codes"
    on public.password_reset_codes for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- users_groups / users_user_permissions
-- Django's PermissionsMixin many-to-many join tables. auth.Group and
-- auth.Permission are Django's OWN built-in tables (auth_group,
-- auth_permission) — created later by the 'auth' app's migrations, not
-- by this file. Not used by any view in this project today; present
-- only because AbstractBaseUser + PermissionsMixin always defines them,
-- and Django's admin site (at /admin/, separate from this project's
-- /admins/) reads them.
--
-- Deliberately no `references public.auth_group/auth_permission` here:
-- this file runs before Django's own `auth` app has created those
-- tables (that's what "relation public.auth_group does not exist"
-- means if you hit it — auth_group/auth_permission are Django's to
-- create, on its first `python manage.py migrate`, not this file's).
-- group_id/permission_id are left as plain integers; Django manages the
-- real relationship in code and never actually re-runs this table's
-- DDL once `--fake-initial` marks it applied, so no constraint is lost
-- versus the recommended (migrate-only) path.
-- ---------------------------------------------------------------------
create table if not exists public.users_groups (
    id       bigint generated by default as identity primary key,
    user_id  bigint not null references public.users (id) on delete cascade,
    group_id integer not null,
    unique (user_id, group_id)
);

create table if not exists public.users_user_permissions (
    id            bigint generated by default as identity primary key,
    user_id       bigint not null references public.users (id) on delete cascade,
    permission_id integer not null,
    unique (user_id, permission_id)
);


-- ==========================================================================
-- Row Level Security — deny-by-default; only a privileged role (Django's
-- DATABASE_URL connection, or Supabase's service_role) can read/write.
-- ==========================================================================
alter table public.users                  enable row level security;
alter table public.role_approval_logs     enable row level security;
alter table public.users_groups           enable row level security;
alter table public.users_user_permissions enable row level security;

-- drop-then-create (rather than "if not exists", which create policy has
-- no syntax for) so this whole file can be re-run safely, e.g. after
-- fixing a typo or re-running following an earlier error partway through.
drop policy if exists "service_role full access to users" on public.users;
create policy "service_role full access to users"
    on public.users for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to role_approval_logs" on public.role_approval_logs;
create policy "service_role full access to role_approval_logs"
    on public.role_approval_logs for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to users_groups" on public.users_groups;
create policy "service_role full access to users_groups"
    on public.users_groups for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to users_user_permissions" on public.users_user_permissions;
create policy "service_role full access to users_user_permissions"
    on public.users_user_permissions for all
    to service_role
    using (true) with check (true);

-- No policy is created for anon/authenticated: with RLS enabled and no
-- matching policy, Supabase's PostgREST/anon-key API sees zero rows and
-- can write nothing, by default. Django itself is unaffected either way —
-- it connects with the role from DATABASE_URL, which owns these tables.


-- ---------------------------------------------------------------------
-- applications
-- Mirrors applicant_dashboard.models.Application. One row per Universal
-- Research Ethics Application submission (templates/dashboards/applicant/
-- application-form.html). The form has ~90 fields across 15 sections that
-- vary a lot by study type, so every posted field lands in `form_data`
-- (jsonb) keyed by its form `name`, keeping only the handful of columns
-- other views/queries actually need as real columns. Uploaded documents
-- go to the "application" Supabase Storage bucket (applicant_dashboard/
-- storage.py) and are recorded in `documents` as
-- [{"name", "path", "size", "content_type"}, ...].
-- ---------------------------------------------------------------------
create table if not exists public.applications (
    id             bigint generated by default as identity primary key,
    applicant_id   bigint not null references public.users (id) on delete cascade,

    -- Assigned once, right after the row first gets its id -- see
    -- Application.assign_reference_no(). NULL (not '') until then: a
    -- unique constraint treats every '' as equal, so a second draft (or
    -- any pre-assignment row) would collide on save; NULL is exempt from
    -- a unique constraint (Postgres allows any number of them).
    reference_no   varchar(40) unique,

    review_type    varchar(40) not null default '',
    status         varchar(20) not null default 'draft'
                   check (status in ('draft', 'submitted', 'under_review', 'revisions_required', 'approved', 'not_approved')),

    form_data      jsonb not null default '{}'::jsonb,
    documents      jsonb not null default '[]'::jsonb,

    -- Client-computed "answered / visible fields" heuristic from apply.js's
    -- updateProgress(), sent with every autosave -- lets the Drafts list
    -- show/sort completion without re-parsing form_data. Meaningless once
    -- status != 'draft' (submit forces it to 100).
    completion_pct smallint not null default 0,

    submitted_at   timestamptz,
    -- Set once, when the Secretariat moves this application to approved or
    -- not_approved (secretariat_dashboard.views) -- the real decision date
    -- shown on Approved Studies / Not Approved (not updated_at, which also
    -- moves on every other status change).
    decided_at     timestamptz,

    -- Revisions round-trip -- set by applicant_dashboard.oversight.apply_transition()
    -- when the Secretariat requests revisions (revision_comment is their
    -- optional note on what to fix), and by application_form when the
    -- applicant fixes and resends. resubmitted_at is the "revision was
    -- done on this application" indicator shown across every applications
    -- list/detail page; revision_count keeps incrementing across rounds
    -- and is never reset, even once the application is later decided.
    revision_comment       text not null default '',
    revision_requested_at  timestamptz,
    revision_count         smallint not null default 0,
    resubmitted_at         timestamptz,

    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

comment on table public.applications is 'MSREC ethics application submissions. applicant_dashboard.models.Application maps onto this table 1:1.';
comment on column public.applications.form_data is 'Every named field from the application form, as posted -- see applicant_dashboard.views._collect_form_data.';
comment on column public.applications.documents is 'Uploaded documents: object paths inside the "application" Storage bucket, plus display metadata.';
comment on column public.applications.resubmitted_at is 'Set only when the applicant actually fixes and resends after a revision request -- NULL means never resubmitted. This is the "revision was done" indicator.';

create index if not exists applications_applicant_id_idx on public.applications (applicant_id);
create index if not exists applications_status_idx on public.applications (status);

alter table public.applications enable row level security;

drop policy if exists "service_role full access to applications" on public.applications;
create policy "service_role full access to applications"
    on public.applications for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- review_assignments
-- Mirrors reviewer_dashboard.models.ReviewAssignment. One row per
-- application handed to one reviewer. Nothing in this project creates
-- these yet (the Secretariat's "Assign Reviewer" flow is still an
-- unbuilt stub link) -- this is the real, empty-until-populated table
-- the Reviewer dashboard's My Reviews page (New / Accepted / Due &
-- Overdue / Completed tabs) reads from and live-polls counts against.
-- ---------------------------------------------------------------------
create table if not exists public.review_assignments (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references public.applications (id) on delete cascade,
    reviewer_id     bigint not null references public.users (id) on delete cascade,
    assigned_by_id  bigint references public.users (id) on delete set null,

    status          varchar(20) not null default 'new'
                    check (status in ('new', 'accepted', 'declined', 'completed')),
    due_date        date,

    assigned_at     timestamptz not null default now(),
    accepted_at     timestamptz,
    declined_at     timestamptz,
    completed_at    timestamptz,

    recommendation  varchar(30) not null default ''
                    check (recommendation in ('', 'approve', 'minor_revisions', 'major_revisions', 'refer_committee', 'not_approved')),
    review_notes    text not null default '',

    -- Whether the reviewer has submitted their conflict-of-interest
    -- declaration for this assignment (drives the "Pending COI
    -- Declarations" stat on the Reviewer dashboard). Set true the moment
    -- the Reviewer Assessment Form below is submitted.
    coi_declared    boolean not null default false,

    -- Reviewer Assessment Form (dashboards/reviewer/review-application.html)
    -- -- one row per assignment, submitted once, then read-only. Mirrors
    -- METASCHOLAR's paper reviewer assessment form section-for-section:
    -- Reviewer Declaration, the 10-row Ethical Review checklist, Reviewer
    -- Comments, and Recommendation.
    coi_has_conflict        boolean not null default false,
    coi_details              text not null default '',
    confidentiality_confirmed boolean not null default false,
    checklist                jsonb not null default '{}'::jsonb,
    key_concerns              text not null default '',
    documents_comment         text not null default '',
    recommendation_reason     text not null default ''
);

comment on table public.review_assignments is 'One application assigned to one reviewer. reviewer_dashboard.models.ReviewAssignment maps onto this table 1:1.';
comment on column public.review_assignments.status is 'new | accepted | declined | completed — an accepted assignment moves itself into the Due & Overdue tab once due_date arrives, without a separate status (see ReviewAssignment.tab).';

create index if not exists review_assignments_reviewer_id_idx on public.review_assignments (reviewer_id);
create index if not exists review_assignments_application_id_idx on public.review_assignments (application_id);
create index if not exists review_assignments_status_idx on public.review_assignments (status);

alter table public.review_assignments enable row level security;

drop policy if exists "service_role full access to review_assignments" on public.review_assignments;
create policy "service_role full access to review_assignments"
    on public.review_assignments for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- inquiries
-- Mirrors pages.models.Inquiry. One row per submission of the public
-- Contact page (templates/pages/contact.html) -- name/email/reason/
-- message go straight to Postgres via the ORM (nothing to upload, so no
-- Storage bucket involved). admin_dashboard's Inquiries page
-- (dashboards/admin/inquiries.html) is where the Secretariat reads and
-- replies to these; replying sets reply_message/replied_at/replied_by,
-- flips status to 'resolved', and emails the reply to the sender.
-- ---------------------------------------------------------------------
create table if not exists public.inquiries (
    id             bigint generated by default as identity primary key,

    name           varchar(150) not null,
    email          varchar(254) not null,
    reason         varchar(30) not null default 'secretariat'
                   check (reason in ('secretariat', 'application-support', 'complaints', 'ethics-concerns', 'technical-support')),
    message        text not null,

    status         varchar(10) not null default 'new'
                   check (status in ('new', 'resolved')),

    reply_message  text not null default '',
    replied_at     timestamptz,
    replied_by_id  bigint references public.users (id) on delete set null,

    created_at     timestamptz not null default now(),
    resolved_at    timestamptz
);

comment on table public.inquiries is 'Public Contact-page submissions. pages.models.Inquiry maps onto this table 1:1.';

create index if not exists inquiries_status_idx on public.inquiries (status);
create index if not exists inquiries_created_at_idx on public.inquiries (created_at desc);

alter table public.inquiries enable row level security;

drop policy if exists "service_role full access to inquiries" on public.inquiries;
create policy "service_role full access to inquiries"
    on public.inquiries for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- conversations / messages / conversation_reads
-- Mirrors messaging.models. Real-time (short-poll) chat between an
-- applicant and the Secretariat -- one conversation per applicant
-- (get-or-create), any admin/secretariat user can open and answer it
-- (see messaging/access.py, not a fixed participant list). Powers
-- dashboards/applicant/messages.html and dashboards/admin/messages.html.
-- ---------------------------------------------------------------------
create table if not exists public.conversations (
    id             bigint generated by default as identity primary key,
    applicant_id   bigint not null unique references public.users (id) on delete cascade,
    created_at     timestamptz not null default now()
);

create table if not exists public.messages (
    id              bigint generated by default as identity primary key,
    conversation_id bigint not null references public.conversations (id) on delete cascade,
    sender_id       bigint not null references public.users (id) on delete cascade,
    body            text not null,
    created_at      timestamptz not null default now()
);

comment on table public.conversations is 'One row per applicant''s support conversation. messaging.models.Conversation maps onto this table 1:1.';
comment on table public.messages is 'Messages within a conversation, oldest first. messaging.models.Message maps onto this table 1:1.';

create index if not exists messages_conversation_id_created_at_idx on public.messages (conversation_id, created_at);

-- Per-user last-read marker -- one row per (conversation, user), not one
-- per message, so unread counts stay a single indexed query.
create table if not exists public.conversation_reads (
    id              bigint generated by default as identity primary key,
    conversation_id bigint not null references public.conversations (id) on delete cascade,
    user_id         bigint not null references public.users (id) on delete cascade,
    last_read_at    timestamptz,
    unique (conversation_id, user_id)
);

alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.conversation_reads enable row level security;

drop policy if exists "service_role full access to conversations" on public.conversations;
create policy "service_role full access to conversations"
    on public.conversations for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to messages" on public.messages;
create policy "service_role full access to messages"
    on public.messages for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to conversation_reads" on public.conversation_reads;
create policy "service_role full access to conversation_reads"
    on public.conversation_reads for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- reviewer_conversations / reviewer_messages / reviewer_conversation_reads
-- Mirrors messaging.models' ReviewerConversation/ReviewerMessage/
-- ReviewerConversationRead -- the Secretariat's own side-channel to a
-- reviewer, same one-row-per-person shape as conversations/messages
-- above but kept in separate tables rather than reusing them, since a
-- reviewer conversation is always opened by the Secretariat (a reviewer
-- has no reason to write in first) rather than by the other party.
-- Powers dashboards/secretariat/reviewer-messages.html.
-- ---------------------------------------------------------------------
create table if not exists public.reviewer_conversations (
    id             bigint generated by default as identity primary key,
    reviewer_id    bigint not null unique references public.users (id) on delete cascade,
    created_at     timestamptz not null default now()
);

create table if not exists public.reviewer_messages (
    id              bigint generated by default as identity primary key,
    conversation_id bigint not null references public.reviewer_conversations (id) on delete cascade,
    sender_id       bigint not null references public.users (id) on delete cascade,
    body            text not null,
    created_at      timestamptz not null default now()
);

create index if not exists reviewer_messages_conversation_id_created_at_idx on public.reviewer_messages (conversation_id, created_at);

create table if not exists public.reviewer_conversation_reads (
    id              bigint generated by default as identity primary key,
    conversation_id bigint not null references public.reviewer_conversations (id) on delete cascade,
    user_id         bigint not null references public.users (id) on delete cascade,
    last_read_at    timestamptz,
    unique (conversation_id, user_id)
);

alter table public.reviewer_conversations enable row level security;
alter table public.reviewer_messages enable row level security;
alter table public.reviewer_conversation_reads enable row level security;

drop policy if exists "service_role full access to reviewer_conversations" on public.reviewer_conversations;
create policy "service_role full access to reviewer_conversations"
    on public.reviewer_conversations for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to reviewer_messages" on public.reviewer_messages;
create policy "service_role full access to reviewer_messages"
    on public.reviewer_messages for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to reviewer_conversation_reads" on public.reviewer_conversation_reads;
create policy "service_role full access to reviewer_conversation_reads"
    on public.reviewer_conversation_reads for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- notifications / notification_reads
-- Mirrors notifications.models. A notification is broadcast to a whole
-- audience (role), not one recipient -- who's currently staffing that
-- role can change, and a notice written for "the Secretariat" should
-- reach whoever that is today. Triggered today by
-- applicant_dashboard.views.application_form() on submit; read by
-- dashboards/secretariat.html's bell dropdown and Notices panel, and
-- composable for any role from secretariat_dashboard's own Notifications
-- page (secretariat_dashboard.views.notifications_page/notification_send).
-- ---------------------------------------------------------------------
create table if not exists public.notifications (
    id             bigint generated by default as identity primary key,
    audience       varchar(20) not null check (audience in ('applicant', 'reviewer', 'committee', 'chair', 'secretariat', 'admin')),
    icon           varchar(10) not null default 'info' check (icon in ('info', 'success', 'warn')),
    message        varchar(255) not null,
    link_url_name  varchar(100) not null default '',
    link_kwargs    jsonb not null default '{}'::jsonb,
    created_at     timestamptz not null default now()
);

create table if not exists public.notification_reads (
    id              bigint generated by default as identity primary key,
    notification_id bigint not null references public.notifications (id) on delete cascade,
    user_id         bigint not null references public.users (id) on delete cascade,
    read_at         timestamptz not null default now(),
    unique (notification_id, user_id)
);

create index if not exists notifications_audience_created_at_idx on public.notifications (audience, created_at desc);

alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;

drop policy if exists "service_role full access to notifications" on public.notifications;
create policy "service_role full access to notifications"
    on public.notifications for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to notification_reads" on public.notification_reads;
create policy "service_role full access to notification_reads"
    on public.notification_reads for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- payments
-- Mirrors payments.models.Payment. One row per Paystack transaction
-- attempt for an application's review fee (payments/fees.py) -- created
-- PENDING the moment an applicant is sent to checkout, *before* Paystack
-- is ever contacted, so there's always a row to reconcile a Paystack
-- callback/verify against. Only ever flipped to 'success' by
-- payments.services.verify_and_finalize() after Paystack's own
-- /transaction/verify/:reference confirms the real amount and currency
-- charged match -- never by anything the browser alone reports. An
-- application only becomes SUBMITTED (applicant_dashboard.views.
-- finalize_submission) once its payment is 'success', for any review
-- type the fee schedule doesn't mark fee-exempt. Read by both
-- secretariat_dashboard's and admin_dashboard's Finance pages.
-- ---------------------------------------------------------------------
create table if not exists public.payments (
    id                 bigint generated by default as identity primary key,
    application_id     bigint references public.applications (id) on delete cascade,
    applicant_id       bigint not null references public.users (id) on delete cascade,

    -- The Django model requires this with no default (payments.models.
    -- Payment.purpose) -- the default '' here only matters if you insert
    -- into this table directly, outside the ORM.
    purpose            varchar(150) not null default '',
    review_type        varchar(40) not null default '',

    -- Our own reference, generated before Paystack is ever contacted --
    -- not Paystack's, so a row to reconcile against always exists even if
    -- Paystack is never reached.
    reference          varchar(100) not null unique,

    amount             numeric(10, 2) not null default 0,
    currency           varchar(8) not null default 'GHS',

    status             varchar(10) not null default 'pending'
                       check (status in ('pending', 'success', 'failed')),

    -- Full verify-transaction payload from Paystack, kept for audit/dispute
    -- purposes (channel, card bin, gateway response, fees charged, ...).
    paystack_response  jsonb not null default '{}'::jsonb,

    created_at         timestamptz not null default now(),
    paid_at            timestamptz
);

comment on table public.payments is 'MSREC application review-fee payments via Paystack. payments.models.Payment maps onto this table 1:1.';
comment on column public.payments.status is 'pending | success | failed -- only payments.services.verify_and_finalize() (server-side Paystack verify) may set success.';

create index if not exists payments_applicant_id_idx on public.payments (applicant_id);
create index if not exists payments_application_id_idx on public.payments (application_id);
create index if not exists payments_status_idx on public.payments (status);

alter table public.payments enable row level security;

drop policy if exists "service_role full access to payments" on public.payments;
create policy "service_role full access to payments"
    on public.payments for all
    to service_role
    using (true) with check (true);

-- ---------------------------------------------------------------------
-- fee_settings
-- Mirrors payments.models.FeeSetting. The live, admin-editable
-- review-fee schedule -- one row per application-form `requestedReview`
-- value. payments/fees.py reads this (never a hardcoded constant) so a
-- price change from the admin Finance page's Fee Schedule editor takes
-- effect immediately, both for what a new checkout actually charges and
-- for what the application form shows an applicant while they're filling
-- it in. Seeded once via payments/migrations/0003_seed_fee_settings.py
-- with the amounts already published on payments-fees.html; the admin
-- Finance page is the only way these change from there on.
-- ---------------------------------------------------------------------
create table if not exists public.fee_settings (
    id             bigint generated by default as identity primary key,
    review_type    varchar(40) not null unique,
    label          varchar(150) not null,
    amount         numeric(10, 2) not null default 0,
    currency       varchar(8) not null default 'GHS',

    updated_at     timestamptz not null default now(),
    updated_by_id  bigint references public.users (id) on delete set null
);

comment on table public.fee_settings is 'MSREC review-fee schedule, admin-editable from the admin Finance page. payments.models.FeeSetting maps onto this table 1:1.';

alter table public.fee_settings enable row level security;

drop policy if exists "service_role full access to fee_settings" on public.fee_settings;
create policy "service_role full access to fee_settings"
    on public.fee_settings for all
    to service_role
    using (true) with check (true);


-- ==========================================================================
-- Incremental migration -- accounts.0005_user_reviewer_availability
-- Run this block on its own in the Supabase SQL editor if `public.users`
-- already exists from an earlier run of this file (the `create table if
-- not exists public.users` above is a no-op on an existing table, so it
-- won't add this column for you). Safe to re-run.
-- ==========================================================================
alter table public.users
    add column if not exists reviewer_availability varchar(20) not null default 'available';

alter table public.users
    drop constraint if exists users_reviewer_availability_check;
alter table public.users
    add constraint users_reviewer_availability_check
    check (reviewer_availability in ('available', 'limited', 'unavailable'));

comment on column public.users.reviewer_availability is 'available | limited | unavailable — shown and changed on secretariat_dashboard''s Reviewer Directory, independent of reviewer_status.';


-- ==========================================================================
-- Incremental migration -- accounts.0006_user_wants_applicant
-- Same as above: run this block on its own if `public.users` already
-- exists. `default true` backfills every existing row so accounts
-- created before this column existed keep landing on the Applicant
-- dashboard exactly as before -- only new signups that skip the
-- Applicant checkbox get false. Safe to re-run.
-- ==========================================================================
alter table public.users
    add column if not exists wants_applicant boolean not null default true;

comment on column public.users.wants_applicant is 'Whether Applicant/Researcher was actually ticked at signup — false means this account requested Reviewer/Committee only and gets no Applicant dashboard access while pending.';


-- ==========================================================================
-- Incremental migration -- applicant_dashboard.0005_application_resubmitted_at_and_more
-- Run this block on its own in the Supabase SQL editor if `public.applications`
-- already exists. Safe to re-run.
-- ==========================================================================
alter table public.applications
    add column if not exists revision_comment text not null default '';
alter table public.applications
    add column if not exists revision_requested_at timestamptz;
alter table public.applications
    add column if not exists revision_count smallint not null default 0;
alter table public.applications
    add column if not exists resubmitted_at timestamptz;

comment on column public.applications.resubmitted_at is 'Set only when the applicant actually fixes and resends after a revision request -- NULL means never resubmitted. This is the "revision was done" indicator.';
comment on column public.applications.revision_comment is 'The Secretariat''s optional note on what needs fixing -- set each time request_revisions runs, shown on the applicant''s Revisions Required page and in their notification email.';


-- ==========================================================================
-- Incremental migration -- reviewer_dashboard.0002_reviewassignment_coi_declared
-- Run this block on its own in the Supabase SQL editor if
-- `public.review_assignments` already exists. Safe to re-run.
-- ==========================================================================
alter table public.review_assignments
    add column if not exists coi_declared boolean not null default false;

comment on column public.review_assignments.coi_declared is 'Whether the reviewer has submitted their conflict-of-interest declaration for this assignment -- drives the Reviewer dashboard''s "Pending COI Declarations" stat.';


-- ==========================================================================
-- Incremental migration -- reviewer_dashboard.0003_reviewassignment_declined_at
-- Run this block on its own in the Supabase SQL editor if
-- `public.review_assignments` already exists. Safe to re-run.
-- ==========================================================================
alter table public.review_assignments
    add column if not exists declined_at timestamptz;

comment on column public.review_assignments.declined_at is 'Set when the reviewer declines a New assignment -- the Secretariat is notified and the application goes back on the Assign Reviewer tab.';


-- ==========================================================================
-- Incremental migration -- reviewer_dashboard.0004_reviewassignment_checklist_and_more
-- Run this block on its own in the Supabase SQL editor if
-- `public.review_assignments` already exists. Adds the Reviewer
-- Assessment Form's fields and widens the recommendation check
-- constraint (drops 'reject', adds 'refer_committee' / 'not_approved').
-- Safe to re-run.
-- ==========================================================================
alter table public.review_assignments
    add column if not exists coi_has_conflict boolean not null default false;
alter table public.review_assignments
    add column if not exists coi_details text not null default '';
alter table public.review_assignments
    add column if not exists confidentiality_confirmed boolean not null default false;
alter table public.review_assignments
    add column if not exists checklist jsonb not null default '{}'::jsonb;
alter table public.review_assignments
    add column if not exists key_concerns text not null default '';
alter table public.review_assignments
    add column if not exists documents_comment text not null default '';
alter table public.review_assignments
    add column if not exists recommendation_reason text not null default '';

alter table public.review_assignments
    drop constraint if exists review_assignments_recommendation_check;
alter table public.review_assignments
    add constraint review_assignments_recommendation_check
    check (recommendation in ('', 'approve', 'minor_revisions', 'major_revisions', 'refer_committee', 'not_approved'));

comment on column public.review_assignments.checklist is 'The 10-row Ethical Review checklist, keyed by ReviewAssignment.CHECKLIST_ITEMS -- each value is satisfactory | needs_revision | na.';
comment on column public.review_assignments.coi_has_conflict is 'Reviewer Declaration section: whether a conflict of interest was declared for this specific assignment -- see coi_details for the description.';


-- ---------------------------------------------------------------------
-- governance_members
-- Mirrors pages.models.GovernanceMember. One row per person shown on the
-- public Board & Committee page (templates/pages/board_committee.html) --
-- added, edited and removed from admin_dashboard's Board & Committee
-- page (dashboards/admin/board-committee.html), photo included.
-- ---------------------------------------------------------------------
create table if not exists public.governance_members (
    id              bigint generated by default as identity primary key,
    full_name       varchar(150) not null,
    role_title      varchar(150) not null,
    tag             varchar(150) not null default '',
    "group"         varchar(20) not null
                    check ("group" in ('board', 'committee', 'secretariat')),

    -- Object path inside Supabase Storage's public "profile" bucket
    -- (governance/<id>/photo.<ext>) -- blank means "no photo yet", and
    -- the public page falls back to a colored initials avatar.
    photo_path      varchar(255) not null default '',

    display_order   smallint not null default 0,
    is_active       boolean not null default true,

    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

comment on table public.governance_members is 'One person shown on the public Board & Committee page. Managed from admin_dashboard''s Board & Committee page.';
comment on column public.governance_members."group" is 'board | committee | secretariat';
comment on column public.governance_members.is_active is 'false = unpublished (kept for the record, hidden from the public page) without deleting the row.';

create index if not exists governance_members_group_idx on public.governance_members ("group");

alter table public.governance_members enable row level security;

drop policy if exists "service_role full access to governance_members" on public.governance_members;
create policy "service_role full access to governance_members"
    on public.governance_members for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- site_settings
-- Mirrors pages.models.SiteSettings. The one site-wide configuration
-- row -- logo, public-footer content, Contact page routing addresses,
-- and the Paystack keys actually charged against -- edited from
-- admin_dashboard's Settings page (dashboards/admin/settings.html,
-- admin-only). A true singleton: application code always reads/writes
-- it through SiteSettings.get_solo(), which get-or-creates the row at
-- id = 1; the check constraint below is a belt-and-braces guarantee
-- that a second row can never exist even if something bypasses the ORM.
-- ---------------------------------------------------------------------
create table if not exists public.site_settings (
    id                          bigint primary key default 1 check (id = 1),

    -- Identity / logo
    site_name                  varchar(150) not null default 'MSREC',
    -- Object path inside Supabase Storage's public "profile" bucket
    -- (site/logo.<ext>, see pages/storage.py upload_site_logo()) --
    -- blank means "no custom logo", every template falls back to the
    -- bundled static/assets/img/logo1.png.
    logo_path                  varchar(255) not null default '',

    -- Public-site footer (templates/base.html)
    footer_about                text not null default '',
    footer_address              text not null default '',
    footer_phone                varchar(40)  not null default '',
    footer_email                varchar(254) not null default '',
    social_twitter_url          varchar(200) not null default '',
    social_facebook_url         varchar(200) not null default '',
    social_instagram_url        varchar(200) not null default '',
    social_linkedin_url         varchar(200) not null default '',

    -- Contact page (templates/pages/contact.html) -- one routing
    -- address per pages.models.Inquiry.Reason choice.
    contact_secretariat_email   varchar(254) not null default '',
    contact_applications_email  varchar(254) not null default '',
    contact_complaints_email    varchar(254) not null default '',
    contact_ethics_email        varchar(254) not null default '',
    contact_techsupport_email   varchar(254) not null default '',
    contact_phone               varchar(40)  not null default '',

    -- Payment gateway -- blank means "not overridden here"; the app
    -- falls back to the PAYSTACK_SECRET_KEY/PAYSTACK_PUBLIC_KEY env
    -- vars whenever these are empty (see payments/paystack.py
    -- secret_key() and payments/views.py's pay()).
    paystack_public_key         varchar(150) not null default '',
    paystack_secret_key         varchar(150) not null default '',

    updated_at                  timestamptz not null default now(),
    updated_by_id                bigint references public.users (id) on delete set null
);

comment on table public.site_settings is 'The one site-wide configuration row (logo, footer, Contact page addresses, Paystack keys). pages.models.SiteSettings maps onto this table 1:1 -- always exactly one row, id = 1.';
comment on column public.site_settings.logo_path is 'Object path in the "profile" Storage bucket -- blank falls back to the bundled static logo.';
comment on column public.site_settings.footer_address is 'Free text, one address line per row (org name / parent body / country, or whatever an admin wants) -- rendered with linebreaksbr, not fixed name/line1/line2/country fields.';
comment on column public.site_settings.paystack_secret_key is 'Never sent to any template -- only ever used server-side in payments/paystack.py''s Authorization header. Blank = fall back to the PAYSTACK_SECRET_KEY env var.';

alter table public.site_settings enable row level security;

drop policy if exists "service_role full access to site_settings" on public.site_settings;
create policy "service_role full access to site_settings"
    on public.site_settings for all
    to service_role
    using (true) with check (true);

-- Seeds the one settings row so the app's first SiteSettings.get_solo()
-- call finds it already there instead of racing to create it. Also
-- fine to skip this -- get_solo() creates it on first access either way.
--
-- Values are spelled out explicitly (not left to `default`) because this
-- file is re-runnable against a table Django's own migration already
-- created -- `create table if not exists` is then a no-op, and Django's
-- CharField(default=...) is a Python-side default only, never a real
-- Postgres column DEFAULT. Relying on the column default here would fail
-- with a not-null violation on a Django-created table, exactly as it did
-- with `insert into public.site_settings (id) values (1)`.
insert into public.site_settings (
    id, site_name, logo_path,
    footer_about, footer_address, footer_phone, footer_email,
    social_twitter_url, social_facebook_url, social_instagram_url, social_linkedin_url,
    contact_secretariat_email, contact_applications_email, contact_complaints_email,
    contact_ethics_email, contact_techsupport_email, contact_phone,
    paystack_public_key, paystack_secret_key, updated_at
) values (
    1, 'MSREC', '',
    'Metascholar Research Ethics Committee provides structured ethical review, post-approval oversight and verifiable decisions for researchers and institutions across multiple disciplines.',
    E'Metascholar Research Ethics Committee\nEstablished under Metascholar Limited\nGhana',
    '+1 5589 55488 55', 'secretariat@msrec.org',
    '', '', '', '',
    'secretariat@msrec.org', 'applications@msrec.org', 'complaints@msrec.org',
    'ethics@msrec.org', 'techsupport@msrec.org', '+1 5589 55488 55',
    '', '', now()
)
on conflict (id) do nothing;


-- ---------------------------------------------------------------------
<<<<<<< HEAD
-- postapproval_submissions
-- Mirrors applicant_dashboard.models.PostApprovalSubmission. One row per
-- post-approval item an applicant files against an approved study --
-- amendment, continuing review, progress report, adverse event,
-- deviation, or closure (see the `type` check below) -- all six sharing
-- one table the same way `applications.form_data` collapses one
-- application's ~90 form fields into jsonb instead of a table each.
-- No dedicated Secretariat/Committee review screen exists yet for these;
-- for now they're actioned from /admin/ (see applicant_dashboard/admin.py).
-- ---------------------------------------------------------------------
create table if not exists public.postapproval_submissions (
    id                bigint generated by default as identity primary key,
    application_id    bigint not null references public.applications (id) on delete cascade,
    applicant_id      bigint not null references public.users (id) on delete cascade,

    type              varchar(20) not null
                      check (type in ('amendment', 'continuing_review', 'progress_report', 'adverse_event', 'deviation', 'closure')),
    status            varchar(20) not null default 'submitted'
                      check (status in ('submitted', 'under_review', 'action_required', 'approved', 'acknowledged')),

    -- Type-specific answers, keyed per POSTAPPROVAL_FIELDS[type] in
    -- applicant_dashboard/models.py -- e.g. an adverse_event row has
    -- event_type/date_onset/severity/relatedness/outcome/description.
    form_data         jsonb not null default '{}'::jsonb,

    secretariat_note  text not null default '',

    submitted_at      timestamptz not null default now(),
    decided_at        timestamptz,
    updated_at        timestamptz not null default now()
);

comment on table public.postapproval_submissions is 'Amendments / continuing reviews / progress reports / adverse events / deviations / closures filed against an approved study. applicant_dashboard.models.PostApprovalSubmission maps onto this table 1:1.';
comment on column public.postapproval_submissions.type is 'amendment | continuing_review | progress_report | adverse_event | deviation | closure — which of the six Post-Approval pages this row belongs to.';
comment on column public.postapproval_submissions.status is 'submitted | under_review | action_required | approved | acknowledged.';
comment on column public.postapproval_submissions.form_data is 'Type-specific answers only -- shared fields (application, applicant, type, status) stay as real columns.';

create index if not exists postapproval_submissions_application_id_idx on public.postapproval_submissions (application_id);
create index if not exists postapproval_submissions_applicant_id_idx on public.postapproval_submissions (applicant_id);
create index if not exists postapproval_submissions_type_idx on public.postapproval_submissions (type);
create index if not exists postapproval_submissions_status_idx on public.postapproval_submissions (status);

alter table public.postapproval_submissions enable row level security;

drop policy if exists "service_role full access to postapproval_submissions" on public.postapproval_submissions;
create policy "service_role full access to postapproval_submissions"
    on public.postapproval_submissions for all
=======
-- research_team_members
-- Mirrors applicant_dashboard.models.TeamMember. One row per collaborator
-- an applicant has added/invited to their research team (Research Team
-- page, dashboards/applicant/research-team.html) -- owned by the
-- applicant who added them, not tied to one Application. Adding someone
-- always emails them an accept-invite link (applicant_dashboard.views.
-- _send_team_invite_email); status just tracks whether they've opened it.
-- There's no real login account behind a team member -- accepting an
-- invite only flips status/accepted_at, it never creates a `users` row.
-- ---------------------------------------------------------------------
create table if not exists public.research_team_members (
    id             bigint generated by default as identity primary key,
    applicant_id   bigint not null references public.users (id) on delete cascade,

    full_name      varchar(200) not null,
    email          varchar(254) not null,
    role           varchar(30) not null default 'co_investigator'
                   check (role in ('co_investigator', 'research_assistant', 'statistician', 'other')),
    institution    varchar(200) not null default '',

    -- Object path inside Supabase Storage's "team_member" bucket (public;
    -- see applicant_dashboard/team_storage.py) -- blank means no photo
    -- yet, the template falls back to an initials avatar. This bucket is
    -- not created by this file -- provision it once, as public, from
    -- Storage > New bucket in the Supabase dashboard.
    photo_path     varchar(255) not null default '',

    status         varchar(20) not null default 'pending'
                   check (status in ('pending', 'active')),

    -- Same "one active token per row, reissued on resend" shape as
    -- password_reset_codes, but a clickable link rather than a typed
    -- code. NULL (not '') once cleared -- a unique constraint treats
    -- every '' as equal; Postgres allows any number of NULLs.
    invite_token   varchar(64) unique,
    invited_at     timestamptz,
    accepted_at    timestamptz,

    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

comment on table public.research_team_members is 'One collaborator on an applicant''s research team. applicant_dashboard.models.TeamMember maps onto this table 1:1.';
comment on column public.research_team_members.invite_token is 'Reissued on every "Resend" click -- see TeamMember.issue_invite_token(). NULL once accepted, not required for the invite email/accept flow either way.';

create index if not exists research_team_members_applicant_id_idx on public.research_team_members (applicant_id);
create index if not exists research_team_members_status_idx on public.research_team_members (status);

alter table public.research_team_members enable row level security;

drop policy if exists "service_role full access to research_team_members" on public.research_team_members;
create policy "service_role full access to research_team_members"
    on public.research_team_members for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- email_templates
-- Mirrors communications.models.EmailTemplate. A reusable, editable
-- email body/subject the Secretariat authors once and reuses -- "body"
-- holds plain text with {{ placeholder }} tokens (first_name,
-- reference_no, etc; see EmailTemplate.PLACEHOLDERS), substituted at
-- send time by EmailTemplate.render(), never interpreted as real Django
-- template syntax. Powers dashboards/secretariat/email-templates.html.
-- ---------------------------------------------------------------------
create table if not exists public.email_templates (
    id             bigint generated by default as identity primary key,
    name           varchar(150) not null,
    category       varchar(20) not null default 'general'
                   check (category in ('general', 'welcome', 'decision', 'reminder', 'payment')),
    subject        varchar(200) not null,
    body           text not null,
    is_active      boolean not null default true,
    created_by_id  bigint references public.users (id) on delete set null,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

create index if not exists email_templates_category_idx on public.email_templates (category);

alter table public.email_templates enable row level security;

drop policy if exists "service_role full access to email_templates" on public.email_templates;
create policy "service_role full access to email_templates"
    on public.email_templates for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- announcements
-- Mirrors communications.models.Announcement. A standing, authored
-- notice for one role or everyone ('all' is the one audience value with
-- no matching row in accounts.models.User.Role -- see
-- communications.models.AudienceChoices) -- distinct from `notifications`
-- above in that it's meant to sit visibly on a dashboard for a stretch
-- of time (a policy change, a maintenance window), not a one-line
-- per-event ping. is_live() (starts_at/expires_at/is_active) is
-- evaluated in Python at read time, not enforced here as a constraint.
-- Powers dashboards/secretariat/announcements.html.
-- ---------------------------------------------------------------------
create table if not exists public.announcements (
    id             bigint generated by default as identity primary key,
    audience       varchar(20) not null default 'all'
                   check (audience in ('all', 'applicant', 'reviewer', 'committee', 'chair', 'secretariat', 'admin')),
    title          varchar(200) not null,
    body           text not null,
    is_pinned      boolean not null default false,
    is_active      boolean not null default true,
    starts_at      timestamptz,
    expires_at     timestamptz,
    created_by_id  bigint references public.users (id) on delete set null,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

create index if not exists announcements_audience_idx on public.announcements (audience);

alter table public.announcements enable row level security;

drop policy if exists "service_role full access to announcements" on public.announcements;
create policy "service_role full access to announcements"
    on public.announcements for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- reminders
-- Mirrors communications.models.Reminder. A message the Secretariat
-- schedules now to fire later -- either at a whole role (audience) or,
-- when application_id is set, at that application's own applicant.
-- Firing means a `notifications` row for the audience plus, if
-- send_email, a branded email to every current recipient -- see
-- communications.services.dispatch_reminder/dispatch_due_reminders.
-- Nothing in Postgres or Django fires this on a timer: there's no task
-- queue in this stack, so dispatch_due_reminders() is called
-- opportunistically whenever the Secretariat opens the Reminders page.
-- Powers dashboards/secretariat/reminders.html.
-- ---------------------------------------------------------------------
create table if not exists public.reminders (
    id             bigint generated by default as identity primary key,
    title          varchar(200) not null,
    message        text not null,
    audience       varchar(20) not null default 'applicant'
                   check (audience in ('all', 'applicant', 'reviewer', 'committee', 'chair', 'secretariat', 'admin')),
    application_id bigint references public.applications (id) on delete cascade,
    remind_at      timestamptz not null,
    send_email     boolean not null default true,
    status         varchar(12) not null default 'scheduled'
                   check (status in ('scheduled', 'sent', 'cancelled')),
    created_by_id  bigint references public.users (id) on delete set null,
    created_at     timestamptz not null default now(),
    sent_at        timestamptz
);

create index if not exists reminders_status_remind_at_idx on public.reminders (status, remind_at);

alter table public.reminders enable row level security;

drop policy if exists "service_role full access to reminders" on public.reminders;
create policy "service_role full access to reminders"
    on public.reminders for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- committee_meetings / meeting_documents
-- Mirrors pages.models.CommitteeMeeting / MeetingDocument. One row per
-- scheduled Full Committee / REC meeting, plus its attached documents
-- (agenda, packet, minutes). Managed from the Secretariat's admin
-- Settings page (admin_dashboard's "Meetings & Documents" section);
-- consumed read-only by the Reviewer dashboard's Upcoming Meetings and
-- Meeting Documents / Packets pages. Files live in Supabase Storage's
-- public "ethics" bucket (pages/documents_storage.py) -- downloads are a
-- direct public URL. As with every Storage bucket in this project, it
-- isn't created by this file -- provision it once, as PUBLIC, from
-- Storage > New bucket in the Supabase dashboard.
-- ---------------------------------------------------------------------
create table if not exists public.committee_meetings (
    id             bigint generated by default as identity primary key,
    title          varchar(200) not null,
    scheduled_at   timestamptz not null,
    location       varchar(255) not null default '',
    meeting_link   varchar(200) not null default '',
    agenda         text not null default '',
    notes          text not null default '',
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

create index if not exists committee_meetings_scheduled_at_idx on public.committee_meetings (scheduled_at);

create table if not exists public.meeting_documents (
    id             bigint generated by default as identity primary key,
    meeting_id     bigint not null references public.committee_meetings (id) on delete cascade,
    doc_type       varchar(20) not null default 'other'
                   check (doc_type in ('agenda', 'packet', 'minutes', 'other')),
    title          varchar(200) not null,
    file_path      varchar(255) not null default '',
    file_size      integer not null default 0,
    uploaded_at    timestamptz not null default now()
);

create index if not exists meeting_documents_meeting_id_idx on public.meeting_documents (meeting_id);

comment on table public.committee_meetings is 'Scheduled Full Committee / REC meetings. pages.models.CommitteeMeeting maps onto this table 1:1.';
comment on table public.meeting_documents is 'Agenda/packet/minutes files attached to one committee meeting. pages.models.MeetingDocument maps onto this table 1:1.';

alter table public.committee_meetings enable row level security;
alter table public.meeting_documents enable row level security;

drop policy if exists "service_role full access to committee_meetings" on public.committee_meetings;
create policy "service_role full access to committee_meetings"
    on public.committee_meetings for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to meeting_documents" on public.meeting_documents;
create policy "service_role full access to meeting_documents"
    on public.meeting_documents for all
    to service_role
    using (true) with check (true);


-- ---------------------------------------------------------------------
-- policy_documents
-- Mirrors pages.models.PolicyDocument. One row per MSREC SOP / Reviewer
-- Guidance / Ethics Guideline document -- one table, filtered by
-- `category` for the Reviewer dashboard's three separate Policies &
-- Guidance pages (each its own URL, not tabs on one page). Same public
-- "ethics" bucket as meeting_documents above. Managed from the
-- Secretariat's admin Settings page ("Policy Library" section).
-- ---------------------------------------------------------------------
create table if not exists public.policy_documents (
    id             bigint generated by default as identity primary key,
    category       varchar(20) not null check (category in ('sop', 'guidance', 'ethics')),
    title          varchar(200) not null,
    description    text not null default '',
    version        varchar(20) not null default '',
    file_path      varchar(255) not null default '',
    file_size      integer not null default 0,
    display_order  smallint not null default 0,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

comment on table public.policy_documents is 'MSREC SOP / Reviewer Guidance / Ethics Guideline documents. pages.models.PolicyDocument maps onto this table 1:1.';

create index if not exists policy_documents_category_idx on public.policy_documents (category);

alter table public.policy_documents enable row level security;

drop policy if exists "service_role full access to policy_documents" on public.policy_documents;
create policy "service_role full access to policy_documents"
    on public.policy_documents for all
    to service_role
    using (true) with check (true);


-- ==========================================================================
-- MSREC — Meetings module (Schedule, Calendar, Agenda, Attendance, Quorum,
-- Minutes, Decisions)
-- ==========================================================================
-- Mirrors the `meetings` Django app (meetings/models.py). Distinct from
-- committee_meetings above: that table is the public/Committee-dashboard
-- listing of scheduled Full Committee sessions with attached documents;
-- these five tables are the Secretariat's internal working set for
-- actually running a meeting -- who's invited, whether they showed up,
-- what's on the agenda, whether quorum was met, the minutes, and the
-- decisions that came out of it.
-- ---------------------------------------------------------------------


-- ---------------------------------------------------------------------
-- meetings
-- Mirrors meetings.models.Meeting. One row per scheduled/completed/
-- cancelled meeting. quorum_required = 0 means "not set yet" -- the
-- Quorum page prompts the Secretariat to set it before treating the
-- meeting as quorate/not quorate (see Meeting.is_quorate()).
-- ---------------------------------------------------------------------
create table if not exists public.meetings (
    id                 bigint generated by default as identity primary key,

    title              varchar(200) not null,
    meeting_type       varchar(20) not null default 'full_committee'
                       check (meeting_type in ('full_committee', 'expedited_panel', 'special', 'emergency', 'administrative')),
    description        text not null default '',

    scheduled_at       timestamptz not null,
    duration_minutes   integer not null default 120,

    mode               varchar(10) not null default 'in_person'
                       check (mode in ('in_person', 'virtual', 'hybrid')),
    location           varchar(255) not null default '',
    meeting_link       varchar(200) not null default '',

    quorum_required    integer not null default 0,

    chair_id           bigint references public.users (id) on delete set null,
    status             varchar(12) not null default 'scheduled'
                       check (status in ('scheduled', 'completed', 'cancelled')),

    created_by_id      bigint references public.users (id) on delete set null,
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);

comment on table public.meetings is 'One Secretariat/Committee meeting -- Schedule Meeting page. meetings.models.Meeting maps onto this table 1:1.';

create index if not exists meetings_scheduled_at_idx on public.meetings (scheduled_at);
create index if not exists meetings_status_idx on public.meetings (status);
create index if not exists meetings_chair_id_idx on public.meetings (chair_id);
create index if not exists meetings_created_by_id_idx on public.meetings (created_by_id);


-- ---------------------------------------------------------------------
-- meeting_participants
-- Mirrors meetings.models.MeetingParticipant. Who's invited to a meeting,
-- their RSVP, and whether they actually attended -- this one table
-- powers both the Attendance page (attended/checked_in_at) and the
-- Quorum page (count of is_voting=true rows with attended=true against
-- meetings.quorum_required). Scheduling a meeting inserts one row per
-- selected participant and emails each of them an invitation
-- (meetings.services.send_meeting_invites).
-- ---------------------------------------------------------------------
create table if not exists public.meeting_participants (
    id               bigint generated by default as identity primary key,
    meeting_id       bigint not null references public.meetings (id) on delete cascade,
    user_id          bigint not null references public.users (id) on delete cascade,

    role_at_meeting  varchar(12) not null default 'member'
                     check (role_at_meeting in ('chair', 'member', 'secretary', 'guest')),
    is_voting        boolean not null default true,

    rsvp_status      varchar(10) not null default 'pending'
                     check (rsvp_status in ('pending', 'accepted', 'declined', 'tentative')),
    invited_at       timestamptz not null default now(),
    responded_at     timestamptz,

    attended         boolean not null default false,
    checked_in_at    timestamptz,

    unique (meeting_id, user_id)
);

comment on table public.meeting_participants is 'Who is invited to a meeting, their RSVP and attendance. meetings.models.MeetingParticipant maps onto this table 1:1.';

create index if not exists meeting_participants_meeting_id_idx on public.meeting_participants (meeting_id);
create index if not exists meeting_participants_user_id_idx on public.meeting_participants (user_id);


-- ---------------------------------------------------------------------
-- meeting_agenda_items
-- Mirrors meetings.models.AgendaItem. What gets discussed at a meeting,
-- in order, optionally tied to one Application under review -- powers
-- the Agenda page and is referenced from Decision.agenda_item below.
-- ---------------------------------------------------------------------
create table if not exists public.meeting_agenda_items (
    id                bigint generated by default as identity primary key,
    meeting_id        bigint not null references public.meetings (id) on delete cascade,
    "order"           integer not null default 0,

    title             varchar(255) not null,
    description       text not null default '',
    presenter         varchar(150) not null default '',
    duration_minutes  integer not null default 10,

    application_id    bigint references public.applications (id) on delete set null,
    status            varchar(10) not null default 'pending'
                      check (status in ('pending', 'discussed', 'deferred')),

    constraint meeting_agenda_items_order_check check ("order" >= 0)
);

comment on table public.meeting_agenda_items is 'Ordered agenda items for one meeting, optionally linked to an Application. meetings.models.AgendaItem maps onto this table 1:1.';

create index if not exists meeting_agenda_items_meeting_id_idx on public.meeting_agenda_items (meeting_id);
create index if not exists meeting_agenda_items_application_id_idx on public.meeting_agenda_items (application_id);


-- ---------------------------------------------------------------------
-- meeting_minutes
-- Mirrors meetings.models.MeetingMinutes. One narrative record per
-- meeting -- Minutes page. Finalizing sets is_finalized/finalized_at and
-- (if the meeting date has passed) flips the parent meeting to
-- status='completed' (see secretariat_dashboard.views.minutes_finalize).
-- ---------------------------------------------------------------------
create table if not exists public.meeting_minutes (
    id             bigint generated by default as identity primary key,
    meeting_id     bigint not null unique references public.meetings (id) on delete cascade,
    content        text not null default '',

    recorded_by_id bigint references public.users (id) on delete set null,
    is_finalized   boolean not null default false,
    finalized_at   timestamptz,

    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

comment on table public.meeting_minutes is 'The written record of one meeting. meetings.models.MeetingMinutes maps onto this table 1:1.';


-- ---------------------------------------------------------------------
-- meeting_decisions
-- Mirrors meetings.models.Decision. The recorded outcome of one agenda
-- item / application discussion, with a vote tally -- Decisions page.
-- ---------------------------------------------------------------------
create table if not exists public.meeting_decisions (
    id               bigint generated by default as identity primary key,
    meeting_id       bigint not null references public.meetings (id) on delete cascade,
    agenda_item_id   bigint references public.meeting_agenda_items (id) on delete set null,
    application_id   bigint references public.applications (id) on delete set null,

    title            varchar(255) not null,
    outcome          varchar(20) not null default 'noted'
                     check (outcome in ('approved', 'approved_conditions', 'modifications', 'rejected', 'deferred', 'tabled', 'noted')),
    details          text not null default '',

    votes_for        integer not null default 0,
    votes_against    integer not null default 0,
    votes_abstain    integer not null default 0,

    decided_at       timestamptz not null default now(),
    recorded_by_id   bigint references public.users (id) on delete set null,
    created_at       timestamptz not null default now()
);

comment on table public.meeting_decisions is 'A recorded committee decision/outcome, with vote tally. meetings.models.Decision maps onto this table 1:1.';

create index if not exists meeting_decisions_meeting_id_idx on public.meeting_decisions (meeting_id);
create index if not exists meeting_decisions_agenda_item_id_idx on public.meeting_decisions (agenda_item_id);
create index if not exists meeting_decisions_application_id_idx on public.meeting_decisions (application_id);


-- ---------------------------------------------------------------------
-- RLS -- same deny-by-default-with-service_role-bypass posture as every
-- other table in this file (see the note at the top of this file).
-- ---------------------------------------------------------------------
alter table public.meetings enable row level security;
alter table public.meeting_participants enable row level security;
alter table public.meeting_agenda_items enable row level security;
alter table public.meeting_minutes enable row level security;
alter table public.meeting_decisions enable row level security;

drop policy if exists "service_role full access to meetings" on public.meetings;
create policy "service_role full access to meetings"
    on public.meetings for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to meeting_participants" on public.meeting_participants;
create policy "service_role full access to meeting_participants"
    on public.meeting_participants for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to meeting_agenda_items" on public.meeting_agenda_items;
create policy "service_role full access to meeting_agenda_items"
    on public.meeting_agenda_items for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to meeting_decisions" on public.meeting_decisions;
create policy "service_role full access to meeting_decisions"
    on public.meeting_decisions for all
    to service_role
    using (true) with check (true);

drop policy if exists "service_role full access to meeting_minutes" on public.meeting_minutes;
create policy "service_role full access to meeting_minutes"
    on public.meeting_minutes for all
    to service_role
    using (true) with check (true);


-- ==========================================================================
-- MSREC — Committee governance (Membership/Appointments, Terms & Expiry,
-- Training, Conflict Records)
-- ==========================================================================
-- Mirrors pages.models.CommitteeAppointment / TrainingRecord /
-- ConflictDeclaration. All three hang off governance_members (above) --
-- one appointment history, one training history and one conflict-of-
-- interest history per Board/Committee member. Managed from
-- admin_dashboard's Committee section; files (appointment letters,
-- training certificates) live in Supabase Storage's public "ethics"
-- bucket (pages/documents_storage.py), same as committee_meetings /
-- policy_documents above.
-- ---------------------------------------------------------------------

create table if not exists public.committee_appointments (
    id             bigint generated by default as identity primary key,
    member_id      bigint not null references public.governance_members (id) on delete cascade,
    seat_title     varchar(150) not null,
    appointed_by   varchar(150) not null default '',
    start_date     date not null,
    end_date       date,
    status         varchar(12) not null default 'active'
                   check (status in ('active', 'renewed', 'expired', 'terminated')),
    notes          text not null default '',
    letter_path    varchar(255) not null default '',
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

create index if not exists committee_appointments_member_id_idx on public.committee_appointments (member_id);
create index if not exists committee_appointments_end_date_idx on public.committee_appointments (end_date);

comment on table public.committee_appointments is 'Appointment/term history for a Board or Committee member -- one row per seat/term. pages.models.CommitteeAppointment maps onto this table 1:1. Membership/Appointments and Terms & Expiry (admin_dashboard) are both views onto this same table.';

alter table public.committee_appointments enable row level security;

drop policy if exists "service_role full access to committee_appointments" on public.committee_appointments;
create policy "service_role full access to committee_appointments"
    on public.committee_appointments for all
    to service_role
    using (true) with check (true);


create table if not exists public.committee_training_records (
    id                 bigint generated by default as identity primary key,
    member_id          bigint not null references public.governance_members (id) on delete cascade,
    course_title       varchar(200) not null,
    provider           varchar(150) not null default '',
    completed_date     date,
    expiry_date        date,
    notes              text not null default '',
    certificate_path   varchar(255) not null default '',
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);

create index if not exists committee_training_records_member_id_idx on public.committee_training_records (member_id);
create index if not exists committee_training_records_expiry_date_idx on public.committee_training_records (expiry_date);

comment on table public.committee_training_records is 'Training/certification history for a Board or Committee member (GCP, human subjects protection, etc). pages.models.TrainingRecord maps onto this table 1:1.';

alter table public.committee_training_records enable row level security;

drop policy if exists "service_role full access to committee_training_records" on public.committee_training_records;
create policy "service_role full access to committee_training_records"
    on public.committee_training_records for all
    to service_role
    using (true) with check (true);


create table if not exists public.committee_conflict_declarations (
    id                 bigint generated by default as identity primary key,
    member_id          bigint not null references public.governance_members (id) on delete cascade,
    application_id     bigint references public.applications (id) on delete set null,
    related_to         varchar(200) not null default '',
    date_declared      date not null default current_date,
    description        text not null,
    status             varchar(12) not null default 'pending'
                       check (status in ('pending', 'reviewed', 'recused', 'resolved')),
    resolution_notes   text not null default '',
    resolved_at        timestamptz,
    recorded_by_id     bigint references public.users (id) on delete set null,
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);

create index if not exists committee_conflict_declarations_member_id_idx on public.committee_conflict_declarations (member_id);
create index if not exists committee_conflict_declarations_status_idx on public.committee_conflict_declarations (status);

comment on table public.committee_conflict_declarations is 'Conflict-of-interest declarations against a Board or Committee member, tracked through to resolution. pages.models.ConflictDeclaration maps onto this table 1:1.';

alter table public.committee_conflict_declarations enable row level security;

drop policy if exists "service_role full access to committee_conflict_declarations" on public.committee_conflict_declarations;
create policy "service_role full access to committee_conflict_declarations"
    on public.committee_conflict_declarations for all
>>>>>>> 9e82dbf56602c998c6309bd331a8d3acee436cea
    to service_role
    using (true) with check (true);
