# Generated by Django 4.2.30 on 2026-09-15 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant_dashboard', '0004_application_decided_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='new', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('approve', 'Approve'), ('minor_revisions', 'Minor Revisions'), ('major_revisions', 'Major Revisions'), ('reject', 'Reject')], max_length=30)),
                ('review_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='applicant_dashboard.application')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
