# Generated by Django 4.2.30 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='coi_declared',
            field=models.BooleanField(default=False),
        ),
    ]
