# Generated by Django 4.2.30 on 2026-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_dashboard', '0002_reviewassignment_coi_declared'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
