# Generated by Django 4.2.30 on 2026-09-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewer_dashboard", "0003_reviewassignment_declined_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewassignment",
            name="checklist",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="coi_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="coi_has_conflict",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="confidentiality_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="documents_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="key_concerns",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="recommendation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="reviewassignment",
            name="recommendation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approve", "Approve"),
                    ("minor_revisions", "Approve Subject to Minor Revisions"),
                    (
                        "major_revisions",
                        "Major Revisions Required / Resubmission Required",
                    ),
                    ("refer_committee", "Refer for Full Committee Review"),
                    ("not_approved", "Not Approved"),
                ],
                max_length=30,
            ),
        ),
    ]
