# Generated by Django 4.2.30 on 2026-09-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewer_dashboard', '0004_reviewassignment_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='certificate_awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='certificate_awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_certificates_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
