# Generated by Django 4.2.30 on 2026-09-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_dashboard', '0005_reviewassignment_certificate_awarded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='deadline_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
