"""Import Ghana universities (from GNRS) and government ministries into the
Institution table.  Idempotent: existing rows (matched case-insensitively on
name) are left untouched; only missing ones are added.

Usage:
    python manage.py import_institutions
"""

from django.core.management.base import BaseCommand

from pages.models import Institution

UNIVERSITIES = [
    "Abetifi College of Education",
    "Academic City University",
    "Accra College of Education",
    "Accra College of Medicine",
    "Accra Institute of Technology",
    "Accra Metropolitan University",
    "Accra School of Hygiene, Korle-Bu",
    "Accra Technical University",
    "Ada College of Education",
    "Advance Global University College",
    "African Institute for Mathematical Sciences (AIMS) Ghana",
    "African University of Communication and Business",
    "Agogo Presbyterian College of Education",
    "Akatsi College of Education",
    "Akim State College",
    "Akrofi-Christaller Institute of Theology, Mission and Culture",
    "Akrokerri College of Education",
    "Al-Faruq College of Education",
    "All Nations University",
    "Amen College of Health Sciences",
    "Anglican University College of Technology",
    "Apostolic Church Theological Seminary",
    "Archbishop Porter Girls' Polytechnic",
    "Ashesi University",
    "Assinman Nursing and Midwifery Training College",
    "Atebubu College of Education",
    "Bagabaga College of Education",
    "Baldwin College",
    "Berekum College of Education",
    "BIA Lamplighter College of Education",
    "Bibiani College of Health Sciences",
    "Bluecrest College",
    "BlueCrest University College",
    "Bolgatanga Technical University",
    "Botho University, Ghana Campus",
    "Bunso Cocoa College",
    "C. K. Tedam University of Technology and Applied Sciences",
    "Cape Coast Technical University",
    "Carest College of Health",
    "Catholic Institute of Business Technology",
    "Catholic University of Ghana",
    "Central College of Science and Technology",
    "Central University",
    "China Europe International Business School (Africa Campus)",
    "Christ Apostolic University College",
    "Christ The Teacher College of Education",
    "Christian Service University",
    "College for Community and Organizational Development",
    "College of Community Health Nursing",
    "College of Health and Well-Being",
    "College of Health, Yamfo",
    "College of Integrated Healthcare",
    "College of Medicine and Allied Sciences",
    "College of Nursing and Midwifery, Kubori",
    "College of Nursing and Midwifery, Sampa",
    "College of Nursing, Ntotroso",
    "Community Health Nurses Training College, Tamale",
    "Community Health Nurses Training School, Navrongo",
    "Community Health Nursing and Midwifery Training College, Tanoso",
    "Community Health Nursing Training College, Jirapa",
    "Community Health Nursing Training School, Akim Oda",
    "Concord Business College",
    "CSIR College of Science and Technology",
    "Dambai College of Education",
    "Data Link Institute of Business and Technology",
    "Delexes University College",
    "DHI College of Health and Education",
    "E.P College of Education, Amedzofe",
    "E.P College of Education, Bimbilla",
    "Ear, Nose and Throat Nursing Training School",
    "Enchi College of Education",
    "Ensign Global University",
    "Entrance University of Health Sciences",
    "Entrepreneurship Training Institute",
    "Evangelical Presbyterian University College",
    "Family Health University",
    "Fanaka International University College",
    "Flosam Institute of Nursing and Allied Health Sciences",
    "Fosu College of Education",
    "Fountainhead Christian University College",
    "Gambaga College of Education",
    "Garden City University",
    "Gbewaa College of Education",
    "Ghana Armed Forces Command and Staff College",
    "Ghana Baptist University College",
    "Ghana Christian University College",
    "Ghana Communication Technology University",
    "Ghana Institute of Management and Public Administration",
    "Ghana Insurance College",
    "Ghana Muslim Mission College of Education",
    "Ghana School of Survey and Mapping",
    "Global Theological Seminary",
    "GNAT Institute for Research and Industrial Relations Studies",
    "Good News Theological Seminary",
    "Greenfield University College",
    "Health Access Institute",
    "Heritage Christian College",
    "High Skies College",
    "Ho Technical University",
    "Holy Child College of Education",
    "Holy Eucharist University College",
    "Holy Family Nurses and Midwifery Training College, Berekum",
    "Holy Family Nurses Training College, Nkawkaw",
    "Holy Family Nursing and Midwifery Training College, Kenten-Techiman",
    "Holy Spirit College of Education",
    "Hopkins Health Training Institute, Oda",
    "ILMA Institute of Science and Technology",
    "Institute for Security, Disaster and Emergency Studies (ISDES)",
    "Institute of Business Management and Journalism (IBMJ)",
    "Institute of Development and Technology Management",
    "Institute of Local Government Studies",
    "Islamic Nursing Training School",
    "Islamic University College, Ghana",
    "JACCD Design Institute Africa",
    "Jackson College of Education",
    "Jackson University College",
    "Jayee University College",
    "Justking College",
    "KAAF University",
    "Kessben University College",
    "Kibi College of Education",
    "Kings and Queens Medical College",
    "Kings University College",
    "Klintaps College of Health and Allied Sciences",
    "Knutsford University College",
    "Kofi Annan International Peace Keeping Training Centre",
    "Koforidua Technical University",
    "Kokofu Nursing Training College",
    "Komenda College of Education",
    "Kumasi Technical University",
    "Kwadaso College of Agriculture",
    "Kwame Nkrumah University of Science and Technology",
    "Lakeside University College",
    "Lancaster University Ghana",
    "M-Gibes College of Business and Management",
    "Malaysia University of Science and Technology",
    "Mampong Technical College of Education",
    "Maranatha University College",
    "Margret Marquart Catholic Nurses Training College",
    "Marshalls College",
    "Martin Luther Health Training School, Kintampo",
    "McCoy College of Education",
    "Mercia Business School",
    "Methodist College of Education, Asene-Oda",
    "Methodist Health Training Institute, Afosu",
    "Methodist University Ghana",
    "Midwifery Training College, Bolgatanga",
    "Miezah University College",
    "Millar Institute of Transdisciplinary and Development Studies",
    "Modal College",
    "Mount Mary College of Education",
    "Mountcrest University College",
    "Mountvielle International University College",
    "Mumford Institute of Technology",
    "N. J. Ahmadiyya College of Education",
    "Narh-Bita College",
    "National Defence University",
    "Nduom School of Business and Technology",
    "Neumann College",
    "New Life College",
    "NiBS University",
    "Nightingale School of Nursing",
    "Nsawkaw College of Education",
    "Nurses and Midwives Training College, Tamale",
    "Nursing and Midwifery Training College, Nandom",
    "Nursing and Midwifery Training College KATH, Kumasi",
    "Nursing and Midwifery Training College, Adansi-Fomena",
    "Nursing and Midwifery Training College, Agogo",
    "Nursing and Midwifery Training College, Atibie Kwahu",
    "Nursing and Midwifery Training College, Bole",
    "Nursing and Midwifery Training College, Damongo",
    "Nursing and Midwifery Training College, Dunkwa-on-Offin",
    "Nursing and Midwifery Training College, Goaso",
    "Nursing and Midwifery Training College, Hohoe",
    "Nursing and Midwifery Training College, Keta",
    "Nursing and Midwifery Training College, Kete-Krachi",
    "Nursing and Midwifery Training College, Koforidua",
    "Nursing and Midwifery Training College, Korle Bu",
    "Nursing and Midwifery Training College, Kpembe",
    "Nursing and Midwifery Training College, Mampong Ashanti",
    "Nursing and Midwifery Training College, Odumase Krobo",
    "Nursing and Midwifery Training College, Seikwa",
    "Nursing and Midwifery Training College, Sunyani",
    "Nursing and Midwifery Training College, Tarkwa",
    "Nursing and Midwifery Training College, Tepa",
    "Nursing and Midwifery Training College, Teshie",
    "Nursing and Midwifery Training College, Twifo Praso",
    "Nursing and Midwifery Training College, Zuarungu",
    "Nursing and Midwifery Training School, Gushegu",
    "Nursing Training College, Bolgatanga",
    "Nursing Training College, Ho",
    "Nursing Training College, Lawra",
    "Nursing Training College, Sefwi Wiawso",
    "Nursing Training College, Wa",
    "Nyansapo College",
    "Oak City International College",
    "Offinso College of Education",
    "Oheneba-Dornyo University College of Counselling Psychology",
    "OLA College of Education",
    "Organization Development Institute",
    "OTEC School of Journalism and Communication Studies",
    "Palm University College",
    "Pantang Nursing Training College",
    "Peki College of Education",
    "Pentecost University",
    "Perez University College",
    "Pharmatrust Professional College",
    "Pinnacle College",
    "Potters College, School of Nursing",
    "Premier Nurses Training College",
    "Presbyterian College of Education, Akropong-Akuapem",
    "Presbyterian Midwifery Training College, Duayaw-Nkwanta",
    "Presbyterian Nursing and Midwifery Training College, Dormaa Ahenkro",
    "Presbyterian University, Ghana",
    "Presbyterian Women's College of Education",
    "Psychiatric Nurses Training College, Ankaful",
    "Public Health Nurses' School, Korle-Bu",
    "Radford University College",
    "Rans-Elliot School of Nursing",
    "Redeemer College of Health",
    "Regent University College of Science and Technology",
    "Regentropfen University College",
    "Regional Maritime University",
    "Rosebank International University College",
    "Royal Ann College of Health",
    "SALT University College",
    "Savannah College of Education",
    "Saviour Church Nursing and Midwifery Training College",
    "School of Anaesthesia and Critical Care, Ridge Accra",
    "School of Peri-Operative and Critical Care Nursing",
    "SDA College of Education, Agona-Ashanti",
    "SDA College of Education, Asokore Koforidua",
    "SDA College of Health, Barekese",
    "SDA College of Nursing and Midwifery, Anyinasu Ashanti",
    "SDA Nursing and Midwifery Training College, Agona-Asamang",
    "SDA Nursing and Midwifery Training College, Kwadaso",
    "SIIMT University College",
    "Southshore University College",
    "Spiritan University College",
    "St. Ambrose College of Education",
    "St. Francis College of Education",
    "St. John Bosco College of Education",
    "St. Joseph's College of Education",
    "St. Karol School of Nursing",
    "St. Louis College of Education",
    "St. Mary's College of Health Science",
    "St. Monica's College of Education",
    "St. Patrick's Nursing and Midwifery Training College, Maase Offinso",
    "St. Teresa's College of Education",
    "St. Vincent College of Education",
    "Sunyani Technical University",
    "Takoradi Technical University",
    "Tamale College of Education",
    "Tamale Technical University",
    "Techbridge University College",
    "The University of Skills Training and Entrepreneurial Development",
    "Thrivus University for Biomedical Science and Technology",
    "Trinity Theological Seminary",
    "Tumu College of Education",
    "Unique Citizens College",
    "University College of Agriculture and Environmental Studies",
    "University College of Management Studies",
    "University for Development Studies",
    "University of Applied Management",
    "University of Business and Integrated Development Studies",
    "University of Cape Coast",
    "University of Education, Winneba",
    "University of Energy and Natural Resources",
    "University of Environment and Sustainable Development",
    "University of Ghana",
    "University of Gold Coast",
    "University of Health and Allied Sciences",
    "University of Media, Arts and Communication",
    "University of Mines and Technology",
    "University of Professional Studies, Accra",
    "Valley View University",
    "Wa Technical University/Dr. Hilla Limann Technical University",
    "Webster University, Ghana Campus",
    "Wesley College of Education",
    "West End University College",
    "Wiawso College of Education",
    "Wisconsin International University College",
    "Withrow College",
    "Zenith University College",
]

MINISTRIES = [
    "Ministry of Finance",
    "Ministry of Health",
    "Ministry of the Interior",
    "Ministry of Defence",
    "Ministry of Education",
    "Ministry of Energy and Green Transition",
    "Ministry of Roads and Highways",
    "Ministry of Transport",
    "Ministry of Sports and Recreation",
    "Office of the Attorney-General and Ministry of Justice",
    "Ministry of Lands and Natural Resources",
    "Ministry of Local Government, Chieftaincy and Religious Affairs",
    "Ministry of Foreign Affairs",
    "Ministry of Communication, Digital Technology and Innovations",
    "Ministry of Environment, Science and Technology",
    "Ministry of Youth Development and Empowerment",
    "Ministry of Works, Housing and Water Resources",
    "Ministry of Gender, Children and Social Protection",
    "Ministry of Tourism, Culture and Creative Arts",
    "Ministry of Labour, Jobs and Employment",
    "Ministry of Food and Agriculture",
    "Ministry of Fisheries and Aquaculture",
    "Ministry of Trade, Agribusiness and Industry",
]


class Command(BaseCommand):
    help = "Import GNRS universities and Ghana government ministries into the Institution list (no duplicates)."

    def handle(self, *args, **options):
        # Collect all names to import, deduplicated within the source lists
        incoming = list(dict.fromkeys(UNIVERSITIES + MINISTRIES))

        # Build a set of existing names (lower-cased) for fast O(1) lookup
        existing_lower = {
            name.lower() for name in Institution.objects.values_list("name", flat=True)
        }

        added = 0
        skipped = 0
        for name in incoming:
            if name.lower() in existing_lower:
                skipped += 1
                self.stdout.write(f"  skip  {name}")
            else:
                Institution.objects.create(name=name, display_order=0, is_active=True)
                existing_lower.add(name.lower())
                added += 1
                self.stdout.write(self.style.SUCCESS(f"  add   {name}"))

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone. Added {added} institution(s), skipped {skipped} already-existing."
            )
        )
