# Generated by Django 4.2.30 on 2026-09-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role_title', models.CharField(max_length=150)),
                ('tag', models.CharField(blank=True, max_length=150)),
                ('group', models.CharField(choices=[('board', 'Board'), ('committee', 'Committee'), ('secretariat', 'Secretariat')], max_length=20)),
                ('photo_path', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'governance_members',
                'ordering': ['group', 'display_order', 'full_name'],
            },
        ),
    ]
