# Generated by Django 4.2.30 on 2026-09-15 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0003_seed_governance_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(blank=True, default="MSREC", max_length=150),
                ),
                ("logo_path", models.CharField(blank=True, max_length=255)),
                (
                    "footer_about",
                    models.TextField(
                        blank=True,
                        default="Metascholar Research Ethics Committee provides structured ethical review, post-approval oversight and verifiable decisions for researchers and institutions across multiple disciplines.",
                    ),
                ),
                (
                    "footer_address",
                    models.TextField(
                        blank=True,
                        default="Metascholar Research Ethics Committee\nEstablished under Metascholar Limited\nGhana",
                    ),
                ),
                (
                    "footer_phone",
                    models.CharField(
                        blank=True, default="+1 5589 55488 55", max_length=40
                    ),
                ),
                (
                    "footer_email",
                    models.EmailField(
                        blank=True, default="secretariat@msrec.org", max_length=254
                    ),
                ),
                ("social_twitter_url", models.URLField(blank=True)),
                ("social_facebook_url", models.URLField(blank=True)),
                ("social_instagram_url", models.URLField(blank=True)),
                ("social_linkedin_url", models.URLField(blank=True)),
                (
                    "contact_secretariat_email",
                    models.EmailField(
                        blank=True, default="secretariat@msrec.org", max_length=254
                    ),
                ),
                (
                    "contact_applications_email",
                    models.EmailField(
                        blank=True, default="applications@msrec.org", max_length=254
                    ),
                ),
                (
                    "contact_complaints_email",
                    models.EmailField(
                        blank=True, default="complaints@msrec.org", max_length=254
                    ),
                ),
                (
                    "contact_ethics_email",
                    models.EmailField(
                        blank=True, default="ethics@msrec.org", max_length=254
                    ),
                ),
                (
                    "contact_techsupport_email",
                    models.EmailField(
                        blank=True, default="techsupport@msrec.org", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="+1 5589 55488 55", max_length=40
                    ),
                ),
                ("paystack_public_key", models.CharField(blank=True, max_length=150)),
                ("paystack_secret_key", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_settings_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "site_settings",
            },
        ),
    ]
