# Generated by Django 4.2.30 on 2026-09-16 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_dashboard', '0006_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_seed_committee_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('certificate_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='pages.governancemember')),
            ],
            options={
                'db_table': 'committee_training_records',
                'ordering': ['-completed_date'],
            },
        ),
        migrations.CreateModel(
            name='ConflictDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.CharField(blank=True, max_length=200)),
                ('date_declared', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('recused', 'Member Recused'), ('resolved', 'Resolved')], default='pending', max_length=12)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_declarations', to='applicant_dashboard.application')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_declarations', to='pages.governancemember')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'committee_conflict_declarations',
                'ordering': ['-date_declared'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_title', models.CharField(help_text='e.g. "Committee Member — Health & Biomedical Science"', max_length=150)),
                ('appointed_by', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('letter_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pages.governancemember')),
            ],
            options={
                'db_table': 'committee_appointments',
                'ordering': ['-start_date'],
            },
        ),
    ]
