# Generated by Django 4.2.30 on 2026-09-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_trainingrecord_conflictdeclaration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('application_forms', 'Application Forms'), ('protocol_templates', 'Protocol Templates'), ('consent_templates', 'Consent Templates'), ('reporting_forms', 'Reporting Forms'), ('guidelines', 'Guidelines'), ('faqs', 'FAQs'), ('training', 'Training')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('external_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resource_documents',
                'ordering': ['category', 'display_order', '-created_at'],
            },
        ),
    ]
