# Generated by Django 4.2.30 on 2026-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_resourcedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancemember',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
