# Generated by Django 4.2.30 on 2026-09-18 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0011_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancemember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_seat', to=settings.AUTH_USER_MODEL),
        ),
    ]
