# Generated by Django 4.2.30 on 2026-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_governance_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydocument',
            name='category',
            field=models.CharField(choices=[('sop', 'MSREC SOP'), ('guidance', 'Reviewer Guidance'), ('ethics', 'Ethics Guideline'), ('charter', 'Committee Charter'), ('terms_of_reference', 'Committee Terms of Reference'), ('committee_policy', 'Committee Policy')], max_length=20),
        ),
    ]
