# Generated by Django 4.2.30 on 2026-09-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_policy_committee_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
