# Generated by Django 4.2.30 on 2026-09-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_sitesettings_hero_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedocument',
            name='category',
            field=models.CharField(choices=[('application_forms', 'Application Forms'), ('protocol_templates', 'Protocol Templates'), ('consent_templates', 'Consent Templates'), ('reporting_forms', 'Reporting Forms'), ('guidelines', 'Guidelines'), ('regulatory_authorizations', 'Regulatory Authorizations'), ('faqs', 'FAQs'), ('training', 'Training')], max_length=25),
        ),
    ]
