# Generated by Django 4.2.30 on 2026-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_resourcedocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auth_image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
