# Generated by Django 4.2.30 on 2026-09-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_site_auth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support_escalation_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
