# Generated by Django 4.2.30 on 2026-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_site_support_escalation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chair_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chair_signature_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chair_title',
            field=models.CharField(blank=True, default='Chair of the Committee', max_length=150),
        ),
    ]
