# Generated by Django 4.2.30 on 2026-09-24 10:36

from django.db import migrations, models


# The six questions the Applicants page used to hardcode, so the page reads
# the same after this migration until an admin edits them in Settings.
DEFAULT_FAQS = [
    ("How long does the review process take?",
     "Most exempt and expedited reviews complete within 5 to 12 business days. Full Committee review, reserved for higher-risk studies, typically takes 15 to 21 business days from screening to decision."),
    ("Can I start recruiting participants before approval?",
     "No. Recruitment, data collection and any participant contact may only begin after you receive a formal decision letter confirming approval."),
    ("What happens if my study changes after approval?",
     "Submit an Amendment Review request describing the change. Minor changes are typically reviewed within 5 to 10 business days; substantial changes may require full Committee review."),
    ("Do I need ethics approval for secondary or existing data?",
     "Usually yes, though many secondary-data studies qualify for Exempt Determination. Submit an application and MSREC, not the applicant, will confirm the appropriate pathway."),
    ("Is there a fee waiver for students?",
     "Yes. Review fees are waived for registered students at Metascholar-affiliated institutions, provided the application includes supervisor sign-off."),
    ("How do I check the status of my application?",
     "Log in to the secure applicant portal to track your application status in real time, from screening through decision."),
]


def seed_faqs(apps, schema_editor):
    ApplicantFAQ = apps.get_model("pages", "ApplicantFAQ")
    if ApplicantFAQ.objects.exists():
        return
    for order, (question, answer) in enumerate(DEFAULT_FAQS, start=1):
        ApplicantFAQ.objects.create(question=question, answer=answer, display_order=order)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_site_chair_signatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applicant_faqs',
                'ordering': ['display_order', 'created_at', 'pk'],
            },
        ),
        migrations.RunPython(seed_faqs, migrations.RunPython.noop),
    ]
