# Generated by Django 4.2.30 on 2026-09-24 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0019_applicant_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(default='Ethical approval granted — {reference_no}', max_length=200)),
                ('email_heading', models.CharField(default='Your study has been approved', max_length=200)),
                ('email_body', models.TextField(default='Dear {applicant_name},\n\nCongratulations. The {committee_name} has approved your study “{study_title}” (reference {reference_no}).\n\nYour approval letter and your certificate of ethical clearance are attached to this email. You can also download them at any time from Documents in your applicant dashboard.\n\nYour approval is valid until {valid_until}. Please keep up with your post-approval obligations: amendments before any change to the protocol, progress reports, prompt reporting of adverse events and deviations, and a final report when the study ends.')),
                ('letter_subject', models.CharField(default='Ethical approval — {study_title}', max_length=300)),
                ('letter_salutation', models.CharField(default='Dear {applicant_name},', max_length=200)),
                ('letter_body', models.TextField(default='I write on behalf of the {committee_name} to confirm that your application, submitted under reference {reference_no}, has been reviewed under the {review_pathway} pathway and has been granted ethical approval.\n\nThis approval takes effect from {approval_date} and remains valid until {valid_until}. You may now proceed with the study as described in the approved protocol and supporting documents.')),
                ('letter_conditions_heading', models.CharField(default='Conditions of approval', max_length=120)),
                ('letter_conditions', models.TextField(blank=True, default="Conduct the study as described in the approved protocol and supporting documents.\nObtain the Committee's approval before implementing any amendment, except where immediate action is needed to protect participants.\nReport serious adverse events and protocol deviations to the Committee promptly.\nSubmit a continuing review before {valid_until} if the study will continue beyond that date.\nNotify the Committee when the study is completed or terminated early, and submit a final report.")),
                ('letter_closing', models.TextField(blank=True, default='We wish you every success with your research. Please quote reference {reference_no} in all correspondence about this study.')),
                ('letter_sign_off', models.CharField(default='Yours sincerely,', max_length=120)),
                ('letter_show_summary', models.BooleanField(default=True)),
                ('letter_show_verification', models.BooleanField(default=True)),
                ('cert_title', models.CharField(default='Certificate', max_length=60)),
                ('cert_subtitle', models.CharField(default='of Ethical Clearance', max_length=80)),
                ('cert_intro', models.CharField(default='This is to certify that the research study', max_length=200)),
                ('cert_statement', models.TextField(default='conducted by {investigator} has been independently reviewed by the {committee_name} and is hereby granted ethical clearance under the {review_pathway} pathway.')),
                ('cert_seal_caption', models.CharField(default='ETHICAL CLEARANCE', max_length=24)),
                ('cert_show_reference', models.BooleanField(default=True)),
                ('cert_show_pathway', models.BooleanField(default=True)),
                ('cert_show_approval_date', models.BooleanField(default=True)),
                ('cert_show_valid_until', models.BooleanField(default=True)),
                ('cert_show_verification', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_document_templates',
            },
        ),
    ]
