# Generated by Django 4.2.30 on 2026-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_approval_document_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocumenttemplate',
            name='letter_footer_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='approvaldocumenttemplate',
            name='letter_header_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
