# Generated by Django 4.2.30 on 2026-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_letter_header_footer_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocumenttemplate',
            name='letter_sign_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='approvaldocumenttemplate',
            name='letter_sign_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='approvaldocumenttemplate',
            name='letter_sign_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
