# Generated by Django 4.2.30 on 2026-09-24 16:38

from django.db import migrations, models


# The four training modules the Resources page used to hardcode (with links
# that went nowhere). They become ordinary, editable rows so the Admin and
# the Secretariat control them from the Resources page. No link is invented:
# until one is added, the public card reads "Link coming soon".
DEFAULT_TRAINING = [
    ("Foundations of Research Ethics", "Online course · 2 hrs", "bi-mortarboard-fill",
     "The core principles of respect for persons, beneficence, justice and accountability behind every MSREC decision.", 100),
    ("Good Clinical Practice (GCP)", "Online course · 3 hrs", "bi-clipboard2-pulse",
     "International standards for designing, conducting and reporting trials that involve human participants.", 110),
    ("AI Ethics & Responsible Research", "Online module · 1.5 hrs", "bi-cpu",
     "Bias, transparency, human oversight and participant awareness for studies that involve AI or automated systems.", 120),
    ("Data Protection & Confidentiality", "Online module · 1 hr", "bi-shield-lock",
     "Practical handling of identifiable, sensitive and cross-border data across the research lifecycle.", 130),
]


def seed_training(apps, schema_editor):
    ResourceDocument = apps.get_model("pages", "ResourceDocument")
    for title, label, icon, description, order in DEFAULT_TRAINING:
        if ResourceDocument.objects.filter(category="training", title=title).exists():
            continue
        ResourceDocument.objects.create(
            category="training", title=title, badge_label=label, icon=icon,
            description=description, display_order=order, is_published=True,
        )


# Django drops a column's default after adding it. Keep an empty-string
# default at the database level so an older copy of the app (which doesn't
# know these columns) can still INSERT into resource_documents.
def set_db_defaults(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":  # SQLite has no ALTER COLUMN
        return
    schema_editor.execute("ALTER TABLE resource_documents ALTER COLUMN badge_label SET DEFAULT ''")
    schema_editor.execute("ALTER TABLE resource_documents ALTER COLUMN icon SET DEFAULT 'bi-mortarboard-fill'")


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_letter_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedocument',
            name='badge_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='resourcedocument',
            name='icon',
            field=models.CharField(blank=True, default='bi-mortarboard-fill', max_length=40),
        ),
        migrations.RunPython(set_db_defaults, migrations.RunPython.noop),
        migrations.RunPython(seed_training, migrations.RunPython.noop),
    ]
