# Generated by Django 4.2.30 on 2026-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_resource_training_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
