# Generated by Django 4.2.30 on 2026-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_maintenance_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governancemember',
            name='group',
            field=models.CharField(choices=[('board', 'Board'), ('committee', 'Committee'), ('secretariat', 'Secretariat'), ('reviewer', 'Reviewer')], max_length=20),
        ),
    ]
