# Generated by Django 4.2.30 on 2026-09-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0025_alter_governancemember_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspensionLetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suspend_subject",
                    models.CharField(
                        default="RE: SUSPENSION OF YOUR MSREC ACCOUNT", max_length=300
                    ),
                ),
                (
                    "suspend_body",
                    models.TextField(
                        default="We write to inform you that {account} has been suspended by the MSREC Secretariat/Administration with effect from {effective_date}.\n\nThis decision was taken for the following reason:\n\n{reason}\n\nFor the duration of this suspension you will not be able to sign in to MSREC, and you may not undertake any review, Committee or other activity on behalf of the {committee_name}. Your account and its records are retained, and access may be restored once the matter has been resolved."
                    ),
                ),
                (
                    "ban_subject",
                    models.CharField(
                        default="RE: PERMANENT WITHDRAWAL OF YOUR MSREC ACCOUNT",
                        max_length=300,
                    ),
                ),
                (
                    "ban_body",
                    models.TextField(
                        default="We write to inform you that {account} has been permanently withdrawn by the MSREC Secretariat/Administration with effect from {effective_date}.\n\nThis decision was taken for the following reason:\n\n{reason}\n\nYou will no longer be able to sign in to MSREC, and you may not act, or present yourself, as a member or representative of the {committee_name}. Any outstanding review or Committee responsibilities assigned to you have been withdrawn."
                    ),
                ),
                (
                    "salutation",
                    models.CharField(default="Dear {recipient_name},", max_length=200),
                ),
                (
                    "closing",
                    models.TextField(
                        blank=True,
                        default="If you have any questions about this decision, or believe it was made in error, please contact the Secretariat, quoting this letter.",
                    ),
                ),
                (
                    "sign_off",
                    models.CharField(default="Yours sincerely,", max_length=120),
                ),
                ("header_path", models.CharField(blank=True, max_length=255)),
                ("footer_path", models.CharField(blank=True, max_length=255)),
                ("sign_name", models.CharField(blank=True, max_length=150)),
                ("sign_title", models.CharField(blank=True, max_length=150)),
                ("sign_path", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "suspension_letter_templates",
            },
        ),
    ]
