# Generated by Django 4.2.30 on 2026-09-28 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0026_suspension_letter_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentLetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_path", models.CharField(blank=True, max_length=255)),
                ("footer_path", models.CharField(blank=True, max_length=255)),
                ("sign_name", models.CharField(blank=True, max_length=150)),
                ("sign_title", models.CharField(blank=True, max_length=150)),
                ("sign_path", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer_subject",
                    models.CharField(
                        default="RE: APPOINTMENT AS {role_caps}, METASCHOLAR RESEARCH ETHICS COMMITTEE",
                        max_length=300,
                    ),
                ),
                (
                    "reviewer_body",
                    models.TextField(
                        default="We are pleased to confirm that, following review and approval, you have been appointed as {a_role} of the {committee_name} (MSREC), effective {effective_date}.\n\nYour MSREC Ethics ID is {ethics_id}. Please quote this reference in all correspondence with the Committee.\n\nIn this capacity you are entrusted with the independent, impartial and confidential ethical review of research protocols assigned to you, in accordance with MSREC's governing Charter and Standard Operating Procedures."
                    ),
                ),
                (
                    "committee_subject",
                    models.CharField(
                        default="RE: APPOINTMENT AS {role_caps}, METASCHOLAR RESEARCH ETHICS COMMITTEE",
                        max_length=300,
                    ),
                ),
                (
                    "committee_body",
                    models.TextField(
                        default="We are pleased to confirm that, following review and approval, you have been appointed as {a_role} of the {committee_name} (MSREC), effective {effective_date}.\n\nYour MSREC Ethics ID is {ethics_id}. Please quote this reference in all correspondence with the Committee.\n\nIn this capacity you are entrusted with the independent, impartial and confidential ethical review of research protocols referred to the Committee, and with taking part in Committee meetings, deliberations and decisions, in accordance with MSREC's governing Charter and Standard Operating Procedures."
                    ),
                ),
                (
                    "salutation",
                    models.CharField(default="Dear {first_name},", max_length=200),
                ),
                (
                    "closing",
                    models.TextField(
                        blank=True,
                        default="A Membership Certificate confirming this appointment is enclosed. We look forward to your valued contribution to the Committee's work in support of independent, rigorous and ethical research.",
                    ),
                ),
                (
                    "sign_off",
                    models.CharField(default="Yours sincerely,", max_length=120),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "appointment_letter_templates",
            },
        ),
    ]
