# Generated by Django 4.2.30 on 2026-10-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_appointment_letter_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'institutions',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
