# Generated by Django 4.2.30 on 2026-10-01 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0028_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerActivityReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_path', models.CharField(blank=True, max_length=255)),
                ('footer_path', models.CharField(blank=True, max_length=255)),
                ('sign_name', models.CharField(blank=True, max_length=150)),
                ('sign_title', models.CharField(blank=True, max_length=150)),
                ('sign_path', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_subject', models.CharField(default='REVIEWER ACTIVITY REPORT — {committee_name}', max_length=300)),
                ('report_body', models.TextField(default="This report summarises the ethics-review activity recorded for {recipient_name} (MSREC Ethics ID {ethics_id}) as {a_role} of the {committee_name}, as at {today}.\n\nThe figures below are drawn directly from the Committee's records and reflect every review assignment issued to this reviewer up to the date of this report.")),
                ('salutation', models.CharField(default='Dear {first_name},', max_length=200)),
                ('closing', models.TextField(blank=True, default="This report is issued for the reviewer's own records and may be used as evidence of their contribution to independent research ethics review. It carries no confidential protocol detail. For verification, contact the MSREC Secretariat quoting the Ethics ID above.")),
                ('sign_off', models.CharField(default='Yours sincerely,', max_length=120)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewer_activity_report_templates',
            },
        ),
    ]
