# Generated by Django 4.2.30 on 2026-10-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0029_revieweractivityreporttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="governancemember",
            name="institution",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
