# Generated by Django 4.2.30 on 2026-09-14 10:25

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country_residence', models.CharField(blank=True, max_length=120)),
                ('highest_qualification', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('institution_country', models.CharField(blank=True, max_length=120)),
                ('institution_address', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True)),
                ('no_institution', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('reviewer', 'Reviewer'), ('committee', 'Committee Member'), ('chair', 'Chair'), ('secretariat', 'Secretariat'), ('admin', 'Administrator')], default='applicant', max_length=20)),
                ('wants_reviewer', models.BooleanField(default=False)),
                ('reviewer_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20)),
                ('reviewer_profile', models.JSONField(blank=True, default=dict)),
                ('wants_committee', models.BooleanField(default=False)),
                ('committee_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20)),
                ('committee_profile', models.JSONField(blank=True, default=dict)),
                ('applicant_profile', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('reviewer', 'Reviewer'), ('committee', 'Committee Member'), ('chair', 'Chair'), ('secretariat', 'Secretariat'), ('admin', 'Administrator')], max_length=20)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_approval_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
