# Generated by Django 4.2.30 on 2026-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
