# Generated by Django 4.2.30 on 2026-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_new_signin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_sms',
            field=models.BooleanField(default=False),
        ),
    ]
