# Generated by Django 4.2.30 on 2026-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_faculty_user_hod_email_user_hod_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviewer_availability',
            field=models.CharField(choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
