# Generated by Django 4.2.30 on 2026-09-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_reviewer_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_applicant',
            field=models.BooleanField(default=True),
        ),
    ]
