# Generated by Django 4.2.30 on 2026-09-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_passwordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications_last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_email_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_sms_alerts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_weekly_digest",
            field=models.BooleanField(default=True),
        ),
    ]
