# Generated by Django 4.2.30 on 2026-09-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auditlog'),
        ('accounts', '0008_user_notifications_last_read_at_and_more'),
    ]

    operations = [
    ]
