# Generated by Django 4.2.30 on 2026-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260917_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_ethics_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
