# Generated by Django 4.2.30 on 2026-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_backfill_reviewer_ethics_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
