# Generated by Django 4.2.30 on 2026-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_sms_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapprovallog',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('reviewer', 'Reviewer'), ('committee', 'Committee Member'), ('chair', 'Chair'), ('secretariat', 'Secretariat'), ('admin', 'Administrator'), ('inst_secretary', 'Institutional Secretary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('reviewer', 'Reviewer'), ('committee', 'Committee Member'), ('chair', 'Chair'), ('secretariat', 'Secretariat'), ('admin', 'Administrator'), ('inst_secretary', 'Institutional Secretary')], default='applicant', max_length=20),
        ),
    ]
