# Generated by Django 4.2.30 on 2026-09-18 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0012_governance_member_user'),
        ('applicant_dashboard', '0008_application_applicant_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliberationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'Comment'), ('question', 'Question'), ('concern', 'Concern'), ('support', 'Support')], default='comment', max_length=8)),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation_posts', to='applicant_dashboard.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation_posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='committee_dashboard.deliberationpost')),
            ],
            options={
                'db_table': 'committee_deliberation_posts',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_conflict', models.BooleanField(default=False)),
                ('conflict_type', models.CharField(blank=True, choices=[('financial', 'Financial interest'), ('personal', 'Personal / family relationship'), ('professional', 'Professional collaboration'), ('institutional', 'Same institution / department'), ('supervisory', 'Supervisory relationship'), ('other', 'Other')], max_length=14)),
                ('description', models.TextField(blank=True)),
                ('wants_recusal', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('clear', 'No conflict'), ('pending', 'Awaiting Chair decision'), ('recused', 'Recused'), ('cleared', 'Cleared to participate')], default='clear', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_declarations', to='applicant_dashboard.application')),
                ('conflict_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_declarations', to='pages.conflictdeclaration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'committee_protocol_declarations',
                'unique_together': {('application', 'user')},
            },
        ),
    ]
