# Generated by Django 4.2.30 on 2026-09-16 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_conversation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewer_conversations',
            },
        ),
        migrations.CreateModel(
            name='ReviewerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.reviewerconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reviewer_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewer_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerConversationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_marks', to='messaging.reviewerconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_conversation_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewer_conversation_reads',
            },
        ),
        migrations.AddConstraint(
            model_name='reviewerconversationread',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_reviewer_conversation_read_per_user'),
        ),
    ]
