from django.urls import path
from django.views.generic import TemplateView

app_name = "applicant_dashboard"

urlpatterns = [
    path("", TemplateView.as_view(template_name="dashboards/applicant.html"), name="home"),
    path(
        "applications/new/",
        TemplateView.as_view(template_name="dashboards/applicant/application-new.html"),
        name="application_new",
    ),
    path(
        "applications/drafts/",
        TemplateView.as_view(template_name="dashboards/applicant/application-drafts.html"),
        name="application_drafts",
    ),
    path(
        "applications/submitted/",
        TemplateView.as_view(template_name="dashboards/applicant/application-submitted.html"),
        name="application_submitted",
    ),
    path(
        "applications/under-review/",
        TemplateView.as_view(template_name="dashboards/applicant/application-under-review.html"),
        name="application_under_review",
    ),
    path(
        "applications/revisions/",
        TemplateView.as_view(template_name="dashboards/applicant/application-revisions.html"),
        name="application_revisions",
    ),
    path(
        "applications/approved/",
        TemplateView.as_view(template_name="dashboards/applicant/application-approved.html"),
        name="application_approved",
    ),
    path(
        "applications/not-approved/",
        TemplateView.as_view(template_name="dashboards/applicant/application-not-approved.html"),
        name="application_not_approved",
    ),
    path(
        "post-approval/amendments/",
        TemplateView.as_view(template_name="dashboards/applicant/postapproval-amendments.html"),
        name="postapproval_amendments",
    ),
    path(
        "post-approval/continuing-reviews/",
        TemplateView.as_view(template_name="dashboards/applicant/postapproval-continuing-reviews.html"),
        name="postapproval_continuing_reviews",
    ),
    path(
        "post-approval/progress-reports/",
        TemplateView.as_view(template_name="dashboards/applicant/postapproval-progress-reports.html"),
        name="postapproval_progress_reports",
    ),
    path(
        "post-approval/adverse-events/",
        TemplateView.as_view(template_name="dashboards/applicant/postapproval-adverse-events.html"),
        name="postapproval_adverse_events",
    ),
    path(
        "post-approval/deviations/",
        TemplateView.as_view(template_name="dashboards/applicant/postapproval-deviations.html"),
        name="postapproval_deviations",
    ),
    path(
        "post-approval/closure/",
        TemplateView.as_view(template_name="dashboards/applicant/postapproval-closure.html"),
        name="postapproval_closure",
    ),
    path(
        "documents/submitted/",
        TemplateView.as_view(template_name="dashboards/applicant/documents-submitted.html"),
        name="documents_submitted",
    ),
    path(
        "documents/decision-letters/",
        TemplateView.as_view(template_name="dashboards/applicant/documents-decision-letters.html"),
        name="documents_decision_letters",
    ),
    path(
        "documents/approval-letters/",
        TemplateView.as_view(template_name="dashboards/applicant/documents-approval-letters.html"),
        name="documents_approval_letters",
    ),
    path(
        "documents/certificates-receipts/",
        TemplateView.as_view(template_name="dashboards/applicant/documents-certificates-receipts.html"),
        name="documents_certificates_receipts",
    ),
    path(
        "payments/fees/",
        TemplateView.as_view(template_name="dashboards/applicant/payments-fees.html"),
        name="payments_fees",
    ),
    path(
        "payments/make/",
        TemplateView.as_view(template_name="dashboards/applicant/payments-make.html"),
        name="payments_make",
    ),
    path(
        "payments/history/",
        TemplateView.as_view(template_name="dashboards/applicant/payments-history.html"),
        name="payments_history",
    ),
    path(
        "payments/receipts/",
        TemplateView.as_view(template_name="dashboards/applicant/payments-receipts.html"),
        name="payments_receipts",
    ),
    path(
        "messages/",
        TemplateView.as_view(template_name="dashboards/applicant/messages.html"),
        name="messages",
    ),
    path(
        "notifications/",
        TemplateView.as_view(template_name="dashboards/applicant/notifications.html"),
        name="notifications",
    ),
    path(
        "research-team/",
        TemplateView.as_view(template_name="dashboards/applicant/research-team.html"),
        name="research_team",
    ),
    path(
        "institution/",
        TemplateView.as_view(template_name="dashboards/applicant/institution-affiliation.html"),
        name="institution",
    ),
    path(
        "profile-security/",
        TemplateView.as_view(template_name="dashboards/applicant/profile-security.html"),
        name="profile_security",
    ),
    path(
        "help/",
        TemplateView.as_view(template_name="dashboards/applicant/help-support.html"),
        name="help_support",
    ),
]
