# Generated by Django 4.2.30 on 2026-10-06 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkshopCertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Certificate", max_length=60)),
                (
                    "title_tail",
                    models.CharField(default="of Participation", max_length=80),
                ),
                (
                    "intro",
                    models.CharField(default="This is to certify that", max_length=200),
                ),
                (
                    "body",
                    models.TextField(
                        default="participated in the {workshop} organised by the Metascholar Research Ethics Committee, and is recognised for their active engagement and commitment to advancing ethical research practice."
                    ),
                ),
                ("seal_caption", models.CharField(default="WORKSHOP", max_length=24)),
                ("signatory1_name", models.CharField(blank=True, max_length=150)),
                (
                    "signatory1_title",
                    models.CharField(
                        blank=True, default="Workshop Coordinator", max_length=150
                    ),
                ),
                (
                    "signatory1_signature_path",
                    models.CharField(blank=True, max_length=255),
                ),
                ("signatory2_name", models.CharField(blank=True, max_length=150)),
                ("signatory2_title", models.CharField(blank=True, max_length=150)),
                (
                    "signatory2_signature_path",
                    models.CharField(blank=True, max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workshop_certificate_templates",
            },
        ),
        migrations.CreateModel(
            name="WorkshopRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("wants_certificate", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_required", "No certificate"),
                            ("pending", "Payment pending"),
                            ("success", "Paid"),
                            ("failed", "Payment failed"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="GHS", max_length=10)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("paystack_response", models.JSONField(blank=True, default=dict)),
                ("meeting_link_sent_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_sent_at", models.DateTimeField(blank=True, null=True)),
                ("materials_sent_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_ref", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workshop_registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workshop_title",
                    models.CharField(
                        default="MSREC Research Ethics Workshop", max_length=200
                    ),
                ),
                (
                    "workshop_tagline",
                    models.CharField(
                        blank=True,
                        default="Strengthening ethical research across institutions",
                        max_length=300,
                    ),
                ),
                (
                    "workshop_description",
                    models.TextField(
                        blank=True,
                        default="Join the Metascholar Research Ethics Committee for a practical workshop on research ethics, review pathways and good research practice. Register below to take part.",
                    ),
                ),
                ("banner_image_path", models.CharField(blank=True, max_length=255)),
                ("banner_image_link", models.URLField(blank=True)),
                (
                    "certificate_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=10
                    ),
                ),
                ("fee_currency", models.CharField(default="GHS", max_length=10)),
                ("meeting_link", models.URLField(blank=True)),
                ("materials_file_path", models.CharField(blank=True, max_length=255)),
                ("materials_link", models.URLField(blank=True)),
                ("registration_open", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workshop_settings",
            },
        ),
    ]
