# Generated by Django 4.2.30 on 2026-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopregistration",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshopregistration",
            name="documents_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshopregistration",
            name="download_token",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
