# Generated by Django 4.2.30 on 2026-10-07 05:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0002_workshopregistration_approved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("registration_closes_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("banner_image_path", models.CharField(blank=True, max_length=255)),
                ("banner_image_link", models.URLField(blank=True)),
                (
                    "certificate_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=10
                    ),
                ),
                ("fee_currency", models.CharField(default="GHS", max_length=10)),
                ("meeting_link", models.URLField(blank=True)),
                ("materials_file_path", models.CharField(blank=True, max_length=255)),
                ("materials_link", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("registration_closed", models.BooleanField(default=False)),
                (
                    "cert_title_tail",
                    models.CharField(default="of Participation", max_length=80),
                ),
                (
                    "cert_intro",
                    models.CharField(default="This is to certify that", max_length=200),
                ),
                (
                    "cert_body",
                    models.TextField(
                        default="participated in the {workshop} organised by the Metascholar Research Ethics Committee, and is recognised for their active engagement and commitment to advancing ethical research practice."
                    ),
                ),
                (
                    "cert_seal_caption",
                    models.CharField(default="WORKSHOP", max_length=24),
                ),
                ("cert_sig1_name", models.CharField(blank=True, max_length=150)),
                (
                    "cert_sig1_title",
                    models.CharField(
                        blank=True, default="Workshop Coordinator", max_length=150
                    ),
                ),
                (
                    "cert_sig1_signature_path",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cert_sig2_name", models.CharField(blank=True, max_length=150)),
                (
                    "cert_sig2_title",
                    models.CharField(
                        blank=True, default="Workshop Coordinator", max_length=150
                    ),
                ),
                (
                    "cert_sig2_signature_path",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cert_show_body", models.BooleanField(default=True)),
                ("cert_show_seal", models.BooleanField(default=True)),
                ("cert_show_second_signature", models.BooleanField(default=True)),
                ("cert_show_verification", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workshops",
                "ordering": ["-starts_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workshopregistration",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="workshop.workshop",
            ),
        ),
    ]
