# Generated by Django 4.2.30 on 2026-10-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_seed_default_workshop"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="title_font_size",
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
