# Generated by Django 4.2.30 on 2026-09-14 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, default='', max_length=40, unique=True)),
                ('review_type', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revisions_required', 'Revisions Required'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], default='draft', max_length=20)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
