# Generated by Django 4.2.30 on 2026-09-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completion_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
