# Generated by Django 4.2.30 on 2026-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_dashboard', '0002_application_completion_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reference_no',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True),
        ),
    ]
