# Generated by Django 4.2.30 on 2026-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_dashboard', '0003_alter_application_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
