# Generated by Django 4.2.30 on 2026-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_dashboard', '0004_application_decided_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='revision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='revision_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
