# Generated by Django 4.2.30 on 2026-09-16 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant_dashboard', '0005_application_resubmitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('co_investigator', 'Co-Investigator'), ('research_assistant', 'Research Assistant'), ('statistician', 'Statistician'), ('other', 'Other')], default='co_investigator', max_length=30)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('photo_path', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Invite'), ('active', 'Active')], default='pending', max_length=20)),
                ('invite_token', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research_team_members',
                'ordering': ['-created_at'],
            },
        ),
    ]
