# Generated by Django 4.2.30 on 2026-09-16 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applicant_dashboard", "0005_application_resubmitted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostApprovalSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("amendment", "Amendment"),
                            ("continuing_review", "Continuing Review"),
                            ("progress_report", "Progress Report"),
                            ("adverse_event", "Adverse Event"),
                            ("deviation", "Deviation"),
                            ("closure", "Closure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("action_required", "Action Required"),
                            ("approved", "Approved"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("form_data", models.JSONField(blank=True, default=dict)),
                ("secretariat_note", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postapproval_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postapproval_submissions",
                        to="applicant_dashboard.application",
                    ),
                ),
            ],
            options={
                "db_table": "postapproval_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
