# Generated by Django 4.2.30 on 2026-09-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_dashboard', '0006_postapprovalsubmission'),
        ('applicant_dashboard', '0006_teammember'),
    ]

    operations = [
    ]
