# Generated by Django 4.2.30 on 2026-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_dashboard', '0007_merge_0006_postapprovalsubmission_0006_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_category',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
