# Generated by Django 4.2.30 on 2026-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_dashboard', '0008_application_applicant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('with_committee', 'With Committee'), ('revisions_required', 'Revisions Required'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], default='draft', max_length=20),
        ),
    ]
