# Generated by Django 4.2.30 on 2026-10-01 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFameNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('areas_of_expertise', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('contribution', models.TextField(blank=True)),
                ('reason_for_nomination', models.TextField(blank=True)),
                ('cv_path', models.CharField(blank=True, max_length=500)),
                ('activity_report_path', models.CharField(blank=True, max_length=500)),
                ('supporting_evidence_path', models.CharField(blank=True, max_length=500)),
                ('photo_path', models.CharField(blank=True, max_length=500)),
                ('consent_accurate', models.BooleanField(default=False)),
                ('consent_publish', models.BooleanField(default=False)),
                ('consent_verify', models.BooleanField(default=False)),
                ('hof_member_id', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('certificate_ref', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('letter_ref', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('recognition_year', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_biography', models.TextField(blank=True)),
                ('revision_message', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hof_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hof_nominations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hof_nominations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HofAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hall_of_fame.halloffamenomination')),
            ],
            options={
                'db_table': 'hof_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
