# Generated by Django 4.2.30 on 2026-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('reviewer', 'Reviewer'), ('committee', 'Committee Member'), ('chair', 'Chair'), ('secretariat', 'Secretariat'), ('admin', 'Administrator')], max_length=20),
        ),
    ]
