# Generated by Django 4.2.30 on 2026-09-24 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_alter_notification_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_dismissals',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationdismissal',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_dismissal_per_user'),
        ),
    ]
