-- ============================================================================
-- MSREC: Institutional Secretaries
-- Run in the Supabase SQL Editor ONLY if you are not using
--   python manage.py migrate
-- (the migrations institution_dashboard/0001_initial and accounts/0018 do
-- exactly this). Safe to run more than once. This script:
--   1. creates the `institution_secretaries` table (the invite / activation
--      record behind each Institutional Secretary login account),
--   2. widens the users.role CHECK constraint to allow the new
--      'inst_secretary' role value, and
--   3. marks the matching Django migrations as applied, so `migrate` won't
--      try to run them again.
-- The name / email / institution of a secretary live on their `users` row
-- (role = 'inst_secretary'); this table only tracks their activation link.
-- ============================================================================
BEGIN;

-- 1. The activation-tracker table ------------------------------------------
CREATE TABLE IF NOT EXISTS institution_secretaries (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint      NOT NULL UNIQUE
                   REFERENCES users (id) DEFERRABLE INITIALLY DEFERRED,
    invite_token  varchar(64) NULL UNIQUE,
    invited_at    timestamptz NULL,
    activated_at  timestamptz NULL,
    created_by_id bigint      NULL
                   REFERENCES users (id) DEFERRABLE INITIALLY DEFERRED,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS institution_secretaries_created_by_id_idx
    ON institution_secretaries (created_by_id);

-- 2. Allow the new role value ----------------------------------------------
-- The platform stores roles as plain text in users.role, guarded by a CHECK
-- constraint. Add 'inst_secretary' to the allowed set (14 chars -- fits the
-- existing varchar(20) column, so no column change is needed).
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check
    CHECK ((role)::text = ANY ((ARRAY[
        'applicant', 'reviewer', 'committee', 'chair',
        'secretariat', 'admin', 'inst_secretary'
    ])::text[]));

-- 3. Tell Django these migrations are already applied -----------------------
INSERT INTO django_migrations (app, name, applied)
SELECT 'institution_dashboard', '0001_initial', now()
WHERE NOT EXISTS (
    SELECT 1 FROM django_migrations
     WHERE app = 'institution_dashboard' AND name = '0001_initial'
);

INSERT INTO django_migrations (app, name, applied)
SELECT 'accounts', '0018_alter_roleapprovallog_role_alter_user_role', now()
WHERE NOT EXISTS (
    SELECT 1 FROM django_migrations
     WHERE app = 'accounts'
       AND name = '0018_alter_roleapprovallog_role_alter_user_role'
);

COMMIT;

-- ============================================================================
-- Handy lookups
-- ============================================================================

-- Every Institutional Secretary and whether they've activated yet
--   SELECT u.first_name, u.last_name, u.email, u.institution,
--          s.invited_at, s.activated_at
--     FROM institution_secretaries s
--     JOIN users u ON u.id = s.user_id
--    ORDER BY s.created_at DESC;

-- Applications belonging to one institution (what a secretary sees)
--   SELECT a.reference_no, a.status, a.submitted_at
--     FROM applications a
--     JOIN users u ON u.id = a.applicant_id
--    WHERE lower(u.institution) = lower('University of Ghana')
--      AND a.status <> 'draft'
--    ORDER BY a.submitted_at DESC;

-- ============================================================================
-- Undo (only if you are rolling the code back too)
-- ============================================================================
--   DROP TABLE IF EXISTS institution_secretaries;
--   UPDATE users SET role = 'applicant' WHERE role = 'inst_secretary';
--   ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
--   ALTER TABLE users ADD CONSTRAINT users_role_check
--     CHECK ((role)::text = ANY ((ARRAY['applicant','reviewer','committee',
--            'chair','secretariat','admin'])::text[]));
--   DELETE FROM django_migrations WHERE app='institution_dashboard' AND name='0001_initial';
--   DELETE FROM django_migrations WHERE app='accounts' AND name='0018_alter_roleapprovallog_role_alter_user_role';
