-- ============================================================================
-- MSREC: institutions (the sign-up form's Institution dropdown)
-- Run in the Supabase SQL Editor ONLY if you are not using
--   python manage.py migrate
-- (the migration pages/0028_institution does exactly this). Safe to run
-- more than once. Creates the `institutions` table that backs the
-- Institution dropdown on the Applicant / Reviewer / Committee sign-up
-- sections, managed from Admin Dashboard > Settings > Institutions.
-- ============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS institutions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(200) NOT NULL UNIQUE,
    display_order smallint     NOT NULL DEFAULT 0 CHECK (display_order >= 0),
    is_active     boolean      NOT NULL DEFAULT true,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now()
);

-- Matches the model's Meta.ordering = ["display_order", "name"].
CREATE INDEX IF NOT EXISTS institutions_order_name_idx ON institutions (display_order, name);

-- Tell Django this migration is already applied, so `migrate` won't try again.
INSERT INTO django_migrations (app, name, applied)
SELECT 'pages', '0028_institution', now()
WHERE NOT EXISTS (
    SELECT 1 FROM django_migrations WHERE app = 'pages' AND name = '0028_institution'
);

COMMIT;

-- ============================================================================
-- Handy controls (changes appear in the sign-up dropdown immediately)
-- ============================================================================

-- Seed a few institutions (lower display_order sorts first)
--   INSERT INTO institutions (name, display_order, is_active) VALUES
--     ('University of Ghana',               1, true),
--     ('Kwame Nkrumah University of Science and Technology', 2, true),
--     ('University of Cape Coast',          3, true)
--   ON CONFLICT (name) DO NOTHING;

-- Hide one from the dropdown without deleting it (keeps existing sign-ups intact)
--   UPDATE institutions SET is_active = false WHERE name = 'University of Ghana';

-- Rename / reorder
--   UPDATE institutions SET name = 'University of Ghana, Legon', display_order = 0
--    WHERE name = 'University of Ghana';

-- List what's live, in dropdown order
--   SELECT display_order, name, is_active FROM institutions
--    ORDER BY display_order, name;

-- ============================================================================
-- Undo (drops the table -- only do this if you are rolling the code back too)
-- ============================================================================
--   DROP TABLE IF EXISTS institutions;
--   DELETE FROM django_migrations WHERE app = 'pages' AND name = '0028_institution';
